### ISSUE TITLE
CookieJar not initialized when creating OAuth2 session

### ISSUE THREAD

**Issue by davidmartos96** [appwrite/sdk-for-flutter#1]
I'm testing out the package, awesome work. I found a small issue though. It looks like if the first interaction with the sdk is the `createOAuth2Session` method, the `cookieJar` in the client never gets initialized so it fails with a null error when calling the following:
```dart
client.cookieJar.saveFromResponse(Uri.parse(client.endPoint), cookies);
```

**Comment by eldadfux** [comment]
@bartektartanus i think we should move the cookiejat init from here:
https://github.com/appwrite/sdk-for-flutter/blob/760ff1a632949c41e6f1a9aadbacb4b6a2f93ce1/lib/client.dart#L88

to the constructor, what do you think?

**Comment by eldadfux** [comment]
Created a fix on the SDK-generator. Tested it with both Android and iOS and all requests seems to work fine, even it the first request is for creating a new OAuth session.

Would probably release this early tomorrow morning IL time as v0.2.2.

**Comment by davidmartos96** [comment]
@eldadfux Great, thank you!

**Comment by eldadfux** [comment]
SDK v0.2.2 is out 🍾
