### ISSUE TITLE
🐛 Bug Report: Create document with role

### ISSUE THREAD

**Issue by Faiyyaz** [appwrite/sdk-for-flutter#106]
### 👟 Reproduction steps

When i try to create the document using the role of user id for users collection i am not able to create the user since it is giving permission error.

```
final document = await databases.createDocument(
        databaseId: 'XXX',
        collectionId: 'XXX',
        documentId: id,
        data: {
          'email': email,
          'id': id,
          'name': name,
          'createdAt': DateTime.now().millisecondsSinceEpoch,
          'updatedAt': DateTime.now().millisecondsSinceEpoch,
        },
        permissions: [
          Permission.create(Role.user(id)),
        ],
      );
```

### 👍 Expected behavior

It should create the user document using the role

### 👎 Actual Behavior

It is giving permission issue

### 🎲 Appwrite version

Version 1.0.x

### 💻 Operating system

MacOS

### 🧱 Your Environment

No

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@Faiyyaz, thanks for creating this issue! 🙏 Would you please provide the permission error you're getting?

**Comment by stnguyen90** [comment]
Also, you can't add a create permission on a document since it's ready created. Did you mean to add update permission?

**Comment by Faiyyazk** [comment]
I am planning to create the document only if the users role is admin but i am not able to create it says permission should be either write, read, update or delete. Also if i try to create through rest api then also it is not considering the permission and allowing creation of documents.

**Comment by Faiyyaz** [comment]
I am planning to create the document only if the users role is admin but i am not able to create it says permission should be either write, read, update or delete. Also if i try to create through rest api then also it is not considering the permission and allowing creation of documents.

**Comment by Faiyyaz** [comment]
Please find attached screenshot of the output i am getting while creating the post document.

<img width="1440" alt="Screenshot 2022-11-06 at 2 13 43 PM" src="https://user-images.githubusercontent.com/18116236/200161889-b9370c81-5560-4af8-949c-1dfc907a0afb.png">

<img width="1440" alt="Screenshot 2022-11-06 at 2 13 33 PM" src="https://user-images.githubusercontent.com/18116236/200161882-951ebd36-db7f-4239-96a3-ad9863fe6850.png">

This is the way i have setup the permission settings for the collection

<img width="1440" alt="Screenshot 2022-11-06 at 2 14 30 PM" src="https://user-images.githubusercontent.com/18116236/200161899-e70c4575-331b-44b2-a441-600fdf612db6.png">

**Comment by stnguyen90** [comment]
@Faiyyaz,

> The current user is not authorized to perform the requested action

This error indicates the user does not have rights (they are not in the team with ID `owner`). 

> Invalid permissions

As stated before, you cannot put `Permission.create()` on a document.

**Comment by Faiyyaz** [comment]
I added the user in the team owner too but still facing the same issue.

Also i think we should have create permission on document because suppose in case of ecommerce app only admin users should be able to create document for product, category, etc

**Comment by stnguyen90** [comment]
> I added the user in the team owner too but still facing the same issue.

Would you execute [`teams.list()`](https://appwrite.io/docs/client/teams?sdk=flutter-default#teamsList) before `databases.createDocument()` and share the output?

> Also i think we should have create permission on document because suppose in case of ecommerce app only admin users should be able to create document for product, category, etc

It doesn't make sense to add a create permission on a **Document** because the document would already be created. You only add the create permission on the collection and that controls who can create documents in that collection.

**Comment by stnguyen90** [comment]
Please also share the `owner` Team as JSON (You can get the JSON by opening the team in the Appwrite Console and clicking "View as JSON" under the Team ID.

**Comment by Faiyyaz** [comment]
Hey, please find requested data

[teams.list()](https://appwrite.io/docs/client/teams?sdk=flutter-default#teamsList) output

<img width="1440" alt="code" src="https://user-images.githubusercontent.com/18116236/200565495-b6622340-81ff-4ea8-ac1c-bc82440bdb5e.png">

owner Team as JSON

<img width="1440" alt="teams" src="https://user-images.githubusercontent.com/18116236/200565668-830791e0-69cf-4c1c-bb34-088f91234a79.png">

**Comment by stnguyen90** [comment]
Would you please try to put `team:<ID>` rather than `team:<NAME>`?

**Comment by stnguyen90** [comment]
> Just one query though can we have custom collection id or team id?

@Faiyyaz, yep! You'll need to specify the ID when creating the team or collection.

**Comment by Faiyyaz** [comment]
Okay thanks @stnguyen90 for great support & appwrite team for such a good package

**Comment by Faiyyaz** [comment]
Hey we can't set custom id from appwrite console. Is it correct

**Comment by stnguyen90** [comment]
@Faiyyaz, yes you can. Click on the edit button to the right of the text input.

**Comment by Faiyyaz** [comment]
@stnguyen90 oh okay thank you... will try that
