### ISSUE TITLE
Dart Code Format

### ISSUE THREAD

**Issue by nitishk72** [appwrite/sdk-for-flutter#11]
By default the dart formatter user the indentation of  2 space.
I am working with flutter for a long time and new focus on much of these. 

Today when tried to contribute to this project I found that the complete code gets modified because of the indentation. 

Here modify means, it modifies the indentation of every line. 
Now the problem is if I send a pull request with that many changes then it would be difficult to find my code change.

I am raising this issue so that beginner and intermediate can contribute without having these difficulties.

Here is one issue about two space indentation problem: https://github.com/Dart-Code/Dart-Code/issues/914

PS: I tried to set the default indentation to 4 spaces that are being used in this project but I failed. 
So, I suggest we should go with the default because dart already has a standard formatter.

> There are two files in the SDK which are `enums.dart` and `service.dart` which use 2 space indentation.

Thank you

**Comment by lohanidamodar** [comment]
@eldadfux  I believe best approach to solve this would be to run the dart formatter after generating sdk before pushing changes to github.

**Comment by eldadfux** [comment]
@lohanidamodar I agree this is the best approach on traditional circumstances. Adding this phase to the SDK-Generator will add huge complexity and coupling tp platform specific tools. I think we should just changed the indentation in the Flutter templates.

**Comment by lohanidamodar** [comment]
@eldadfux Are we accepting PR directly on SDKs?
1. Any features, improvements on SDKs, should go to SDK generator
2. Also, this is a code formatting, even if we accept this PR now, next time we generate new SDK this will not work.

Either, these changes will have to be propagated to SDK generator, however I believe that's not necessary, as we discussed above, we can simply run dart formatter every time we generate new version of SDK.

@eldadfux Please let me know if I am missing something.

**Comment by eldadfux** [comment]
@lohanidamodar you are correct. We are not accepting any PRs directly to the SDKs repos. Any change should be submitted to the SDK generator, as stated on the repo, its a read-only repository.

Using the dart formatter on any creation of the SDK will add a lot of complexity to the automated process. It will be much more effective to just fix the indentation in the generator templates for Flutter.

**Comment by nitishk72** [comment]
@eldadfux 
Do I need to make the same PL to this repo https://github.com/appwrite/sdk-generator ?

**Comment by eldadfux** [comment]
@nitishk72 your assumption is correct, but it should be pretty simple once you set a dev environment and understand how to generate an example SDK. A few back and forward iterations should get you the desired result.

**Comment by nitishk72** [comment]
Probably it's difficult for any general developer to contribute, as long as they aren't in deep love with PHP. 
I am a PHP developer for a long time and probably I can do this but I think it's a little lengthy process. I know after 2-3 commit this process will become easier for me.

But again it's not a very good choice because appwrite supports a variety of languages or frameworks. 
All the developers who will come here to contribute, will not surely a PHP developer.

I will suggest you rethink this. 

>How non-php developers will contribute because app write is not limited to PHP only?

**Comment by eldadfux** [comment]
@nitishk72 like anything in life you have advantages and disadvantages. We have been working this way in last year, and ~80% of our SDKs have been written by non-PHP coders. Most of the work on the SDK generator is handling with a language agnostic templates syntax (TWIG) and not actually writing PHP code.

Appwrite is for everyone. Our vision is to build a platform & language agnostic platform but at the end of the day our core-team can jump between 12+ different coding languages.

Again, you are correct about the disadvantages, but  at this period of time this solution works pretty well for us, when it will stop being effective we're always happy to rethink our ideas, designs and ways.

**Comment by eldadfux** [comment]
This fix has already been pushed to the SDK-Generator and is available on v0.3 of our Dart SDK and will be ready for next version of our Flutter dev channel :).
