### ISSUE TITLE
🐛 Bug Report: 401 Uploading File

### ISSUE THREAD

**Issue by sgruhier** [appwrite/sdk-for-flutter#113]
### 👟 Reproduction steps

Upload a file thatwill be send by more than one chunk

### 👍 Expected behavior

It should upload the file

### 👎 Actual Behavior

It raises an error
``` 
Unhandled Exception: AppwriteException: user_unauthorized, The current user is not authorized to perform the requested action. (401)
``` 

Here is the stack trace.

```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: AppwriteException: user_unauthorized, The current user is not authorized to perform the requested action. (401)
[log] AppwriteException: user_unauthorized, The current user is not authorized to perform the requested action. (401)
#0      ClientMixin.prepareResponse
package:appwrite/src/client_mixin.dart:73
#1      ClientIO.call
package:appwrite/src/client_io.dart:351
<asynchronous suspension>
#2      ClientIO.chunkedUpload
package:appwrite/src/client_io.dart:280
<asynchronous suspension>
#3      Storage.createFile
package:appwrite/services/storage.dart:75
```

### 🎲 Appwrite version

Version 2.0.x

### 💻 Operating system

MacOS

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@sgruhier it seems the user doesn't have access to upload to the bucket. What are the permissions on your bucket?

**Comment by stnguyen90** [comment]
@sgruhier have you had a chance to look into your bucket's permissions? FYI, we'll need to close this soon due to inactivity.

**Comment by sgruhier** [comment]
Sorry, thanks! it was really a permission issue
