### ISSUE TITLE
🐛 Bug Report: `CORS` not allowed by web-browsers 🐛

### ISSUE THREAD

**Issue by hemangjoshi37a** [appwrite/sdk-for-flutter#116]
### 👟 Reproduction steps

When I try to make user auth requests on http on my appwrite server which has different web address then my production one it gives me `XLMHttpRequest Error`. 

And I dug a little into this and found that there are some rules that most of the modern browsers have is `CORS` policy to prevent the webpages to make request to different origin addresses.

### 👍 Expected behavior

Should auth users.

### 👎 Actual Behavior

Not authenticating users. and giving  `XLMHttpRequest Error`. 

### 🎲 Appwrite version

Version 2.0.x

### 💻 Operating system

Linux

### 🧱 Your Environment

I use everythign stock, stock ubuntu 22, ann all everything.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@hemangjoshi37a thanks for creating this issue! 🙏🏼 Have you registered your app by adding the flutter platform? FYI, for now, you should register a web app since there's a bug with flutter-web.

**Comment by hemangjoshi37a** [comment]
> @hemangjoshi37a thanks for creating this issue! 🙏🏼 Have you registered your app by adding the flutter platform? FYI, for now, you should register a web app since there's a bug with flutter-web.

I dont know about any registration . What kind of registration we are talking about? How to do it? can you give me any link to this documentaion or any steps you can suggest Please.

**Comment by lohanidamodar** [comment]
@hemangjoshi37a by registration, we mean adding platform as described here in the docs
https://appwrite.io/docs/getting-started-for-flutter#addYourPlatform

**Comment by stnguyen90** [comment]
@hemangjoshi37a, anything else you need, or can this be closed now?

**Comment by hemangjoshi37a** [comment]
> @hemangjoshi37a, anything else you need, or can this be closed now?

Ok can be closed
