### ISSUE TITLE
🐛 Bug Report:  Flutter App fails to compile on android as soon as Appwrite is added as an dependency

### ISSUE THREAD

**Issue by Rohit-RA-2020** [appwrite/sdk-for-flutter#133]
### 👟 Reproduction steps

When I run a new flutter app it launches as expected, but as soon as I re-run the app by adding Appwrite as an dependency it fails to compile. Below is a video indicating the issue.

https://user-images.githubusercontent.com/53489549/225234121-51203aa0-1cc9-4fc4-a215-dcbf2376a0fb.mp4

### 👍 Expected behavior

App should launch perfectly fine even after adding Appwrite as an dependency

### 👎 Actual Behavior

Got these error logs

> FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugDuplicateClasses'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.CheckDuplicatesRunnable
   > Duplicate class kotlin.collections.jdk8.CollectionsJDK8Kt found in modules jetified-kotlin-stdlib-1.8.0 (org.jetbrains.kotlin:kotlin-stdlib:1.8.0) and jetified-kotlin-stdlib-jdk8-1.5.30 (org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.5.30)
     Duplicate class kotlin.internal.jdk8.JDK8PlatformImplementations found in modules jetified-kotlin-stdlib-1.8.0 (org.jetbrains.kotlin:kotlin-stdlib:1.8.0) and jetified-kotlin-stdlib-jdk8-1.5.30 (org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.5.30)
     Duplicate class kotlin.random.jdk8.PlatformThreadLocalRandom found in modules jetified-kotlin-stdlib-1.8.0 (org.jetbrains.kotlin:kotlin-stdlib:1.8.0) and jetified-kotlin-stdlib-jdk8-1.5.30 (org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.5.30)
     Duplicate class kotlin.streams.jdk8.StreamsKt found in modules jetified-kotlin-stdlib-1.8.0 (org.jetbrains.kotlin:kotlin-stdlib:1.8.0) and jetified-kotlin-stdlib-jdk8-1.5.30 (org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.5.30)
     Duplicate class kotlin.streams.jdk8.StreamsKt$asSequence$$inlined$Sequence$1 found in modules jetified-kotlin-stdlib-1.8.0 (org.jetbrains.kotlin:kotlin-stdlib:1.8.0) and jetified-kotlin-stdlib-jdk8-1.5.30 (org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.5.30)
     Duplicate class kotlin.streams.jdk8.StreamsKt$asSequence$$inlined$Sequence$2 found in modules jetified-kotlin-stdlib-1.8.0 (org.jetbrains.kotlin:kotlin-stdlib:1.8.0) and jetified-kotlin-stdlib-jdk8-1.5.30 (org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.5.30)
     Duplicate class kotlin.streams.jdk8.StreamsKt$asSequence$$inlined$Sequence$3 found in modules jetified-kotlin-stdlib-1.8.0 (org.jetbrains.kotlin:kotlin-stdlib:1.8.0) and jetified-kotlin-stdlib-jdk8-1.5.30 (org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.5.30)
     Duplicate class kotlin.streams.jdk8.StreamsKt$asSequence$$inlined$Sequence$4 found in modules jetified-kotlin-stdlib-1.8.0 (org.jetbrains.kotlin:kotlin-stdlib:1.8.0) and jetified-kotlin-stdlib-jdk8-1.5.30 (org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.5.30)
     Duplicate class kotlin.text.jdk8.RegexExtensionsJDK8Kt found in modules jetified-kotlin-stdlib-1.8.0 (org.jetbrains.kotlin:kotlin-stdlib:1.8.0) and jetified-kotlin-stdlib-jdk8-1.5.30 (org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.5.30)
     Duplicate class kotlin.time.jdk8.DurationConversionsJDK8Kt found in modules jetified-kotlin-stdlib-1.8.0 (org.jetbrains.kotlin:kotlin-stdlib:1.8.0) and jetified-kotlin-stdlib-jdk8-1.5.30 (org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.5.30)

     Go to the documentation to learn how to <a href="d.android.com/r/tools/classpath-sync-errors">Fix dependency resolution errors</a>.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

### 🎲 Appwrite version

Version 2.0.x

### 💻 Operating system

Windows

### Below is a snap of my flutter doctor
![Screenshot 2023-03-15 123948](https://user-images.githubusercontent.com/53489549/225233104-c69e9dc8-918f-4442-8d0f-e20ed73da95b.png)

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by lohanidamodar** [comment]
@Rohit-RA-2020 I figured out the issue, this is because one of our dependencies, `flutter_web_auth_2` uses newest version of kotlin version (1.8.0) the quickest solution for now is to update `android/build.gradle`

```
buildscript {
    ext.kotlin_version = '1.8.0'
	...
}
```

**Comment by Rohit-RA-2020** [comment]
##### Yes, that solves the issue but I guess this needs to be fixed as any dependency should work out of the box and many other users of Appwrite or people just getting started with Appwrite might face the same issue .

**Comment by lohanidamodar** [comment]
> ##### Yes, that solves the issue but I guess this needs to be fixed as any dependency should work out of the box and many other users of Appwrite or people just getting started with Appwrite might face the same issue .

Good point. We are working to figure out a solution.

**Comment by ThexXTURBOXx** [comment]
I am terribly sorry for this. I have pushed a new release for `flutter_web_auth_2` which should fix the underlying issue.

**Comment by lohanidamodar** [comment]
@Rohit-RA-2020 with new version for `flutter_web_auth_2` this issue should already be fixed. If not please let us know, we will release another version for `appwrite`

**Comment by Rohit-RA-2020** [comment]
Yes it works like charm now. I think we can close this issue now.
