### ISSUE TITLE
🐛 Bug Report: static Query function invokation return dynamic data type

### ISSUE THREAD

**Issue by Vedsaga** [appwrite/sdk-for-flutter#136]
### 👟 Reproduction steps

Try using below code with strict linting configuration such as `very_good_analyzer` it will not let compile the app.

```dart
Query.equal( 'index', [userDocumentId], ),
```

Version I am using is `appwrite: ^8.3.0`

### 👍 Expected behavior

```dart
Query.equal( 'idx_business_user_id', [userDocumentId], ),
```

Data type return by `equal` should be explicit `String`.

### 👎 Actual Behavior

```dart
Query.equal( 'idx_business_user_id', [userDocumentId], ),
```

Seems to return dynamic data type as you can assign dynamic data type to string.

``` dart
 queries: [
         Query.equal( 'idx_business_user_id', [userDocumentId], ),
],
```

as you can see `queries` expect `List<String>?` but, because ` Query.equal` static function return `dynamic` so, when you use that static function to create query the data type becomes , `List<dynamic>` . And, so strict linting analyzer won't let it compile.
### 🎲 Appwrite version

Different version (specify in environment)

### 💻 Operating system

Windows

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by lohanidamodar** [comment]
@Vedsaga thank you for the report, we will look into it
