### ISSUE TITLE
🐛 Bug Report: pub.dev says appwrite package does not support web

### ISSUE THREAD

**Issue by stnguyen90** [appwrite/sdk-for-flutter#138]
### 👟 Reproduction steps

1. Browse to appwrite on [pub.dev](https://pub.dev/packages/appwrite)

### 👍 Expected behavior

Platform incldues web

### 👎 Actual Behavior

Platform does not include web:

![image](https://user-images.githubusercontent.com/1477010/228973222-c358ff25-90e7-487e-a596-c4f04bb6d979.png)

### 🎲 Appwrite version

Version 2.0.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
[Pana](https://github.com/dart-lang/pana) can be used to see how pub.dev detects:

## ✓ Follow Dart file conventions (30 / 30)
### [*] 10/10 points: Provide a valid `pubspec.yaml`


### [*] 5/5 points: Provide a valid `README.md`


### [*] 5/5 points: Provide a valid `CHANGELOG.md`


### [*] 10/10 points: Use an OSI-approved license

Detected license: `BSD-3-Clause`.

## ✓ Provide documentation (10 / 10)
### [*] 10/10 points: Package has an example


## ✓ Platform support (20 / 20)
### [*] 20/20 points: Supports 5 of 6 possible platforms (**iOS**, **Android**, Web, **Windows**, **MacOS**, **Linux**)

* ✓ Android
* ✓ iOS
* ✓ Windows
* ✓ Linux
* ✓ MacOS

These platforms are not supported:

<details>
<summary>
Package does not support platform `Web`.
</summary>

Because:
* `package:appwrite/appwrite.dart` that imports:
* `package:appwrite/src/realtime.dart` that imports:
* `package:appwrite/src/client.dart` that imports:
* `package:appwrite/src/client_browser.dart` that imports:
* `package:flutter_web_auth_2/flutter_web_auth_2.dart` that imports:
* `package:flutter_web_auth_2/src/flutter_web_auth_2_linux.dart` that imports:
* `package:window_to_front/window_to_front.dart` that declares support for platforms: `Windows`, `Linux`, `macOS`.
</details>

These issues are present but do not affect the score, because they may not originate in your package:

<details>
<summary>
Package does not support platform `Android`.
</summary>

Because:
* `package:appwrite/appwrite.dart` that imports:
* `package:appwrite/src/realtime.dart` that imports:
* `package:appwrite/src/client.dart` that imports:
* `package:appwrite/src/client_io.dart` that imports:
* `package:flutter_web_auth_2/flutter_web_auth_2.dart` that imports:
* `package:flutter_web_auth_2/src/flutter_web_auth_2_windows.dart` that imports:
* `package:window_to_front/window_to_front.dart` that declares support for platforms: `Windows`, `Linux`, `macOS`.
</details>
<details>
<summary>
Package does not support platform `iOS`.
</summary>

Because:
* `package:appwrite/appwrite.dart` that imports:
* `package:appwrite/src/realtime.dart` that imports:
* `package:appwrite/src/client.dart` that imports:
* `package:appwrite/src/client_io.dart` that imports:
* `package:flutter_web_auth_2/flutter_web_auth_2.dart` that imports:
* `package:flutter_web_auth_2/src/flutter_web_auth_2_windows.dart` that imports:
* `package:window_to_front/window_to_front.dart` that declares support for platforms: `Windows`, `Linux`, `macOS`.
</details>
<details>
<summary>
Package does not support platform `Linux`.
</summary>

Because:
* `package:appwrite/appwrite.dart` that imports:
* `package:appwrite/src/realtime.dart` that imports:
* `package:appwrite/src/client.dart` that imports:
* `package:appwrite/src/client_io.dart` that imports:
* `package:package_info_plus/package_info_plus.dart` that imports:
* `package:package_info_plus/src/package_info_plus_windows.dart` that imports:
* `package:win32/win32.dart` that declares support for platforms: `Windows`.
</details>
<details>
<summary>
Package does not support platform `macOS`.
</summary>

Because:
* `package:appwrite/appwrite.dart` that imports:
* `package:appwrite/src/realtime.dart` that imports:
* `package:appwrite/src/client.dart` that imports:
* `package:appwrite/src/client_io.dart` that imports:
* `package:package_info_plus/package_info_plus.dart` that imports:
* `package:package_info_plus/src/package_info_plus_windows.dart` that imports:
* `package:win32/win32.dart` that declares support for platforms: `Windows`.
</details>

## ✗ Pass static analysis (0 / 30)
### [x] 0/30 points: code has no errors, warnings, lints, or formatting issues

* Failed to run `dart analyze`:
```
Analysis failed with unexpected output.
``--[no-]analytics` is deprecated.  Use `--suppress-analytics` to disable analytics for one run instead.`
```


## ✓ Support up-to-date dependencies (20 / 20)
### [*] 10/10 points: All of the package dependencies are supported in the latest version

|Package|Constraint|Compatible|Latest|
|:-|:-|:-|:-|
|[`cookie_jar`]|`^3.0.1`|3.0.1|**4.0.1**|
|[`device_info_plus`]|`^8.1.0`|8.1.0|8.1.0|
|[`flutter`]|`flutter`|0.0.0|0.0.0|
|[`flutter_web_auth_2`]|`^2.0.4`|2.1.2|2.1.2|
|[`http`]|`^0.13.5`|0.13.5|0.13.5|
|[`package_info_plus`]|`^3.0.3`|3.0.3|3.0.3|
|[`path_provider`]|`^2.0.13`|2.0.14|2.0.14|
|[`universal_html`]|`^2.0.9`|2.2.1|2.2.1|
|[`web_socket_channel`]|`^2.3.0`|2.3.0|2.3.0|

<details><summary>Transitive dependencies</summary>

|Package|Constraint|Compatible|Latest|
|:-|:-|:-|:-|
|[`async`]|-|2.11.0|2.11.0|
|[`characters`]|-|1.3.0|1.3.0|
|[`charcode`]|-|1.3.1|1.3.1|
|[`collection`]|-|1.17.1|1.17.1|
|[`crypto`]|-|3.0.2|3.0.2|
|[`csslib`]|-|0.17.2|0.17.2|
|[`device_info_plus_platform_interface`]|-|7.0.0|7.0.0|
|[`ffi`]|-|2.0.1|2.0.1|
|[`file`]|-|6.1.4|6.1.4|
|[`flutter_web_auth_2_platform_interface`]|-|2.1.0|2.1.0|
|[`flutter_web_plugins`]|-|0.0.0|0.0.0|
|[`html`]|-|0.15.2|0.15.2|
|[`http_parser`]|-|4.0.2|4.0.2|
|[`js`]|-|0.6.7|0.6.7|
|[`material_color_utilities`]|-|0.2.0|0.3.0|
|[`meta`]|-|1.9.1|1.9.1|
|[`package_info_plus_platform_interface`]|-|2.0.1|2.0.1|
|[`path`]|-|1.8.3|1.8.3|
|[`path_provider_android`]|-|2.0.24|2.0.24|
|[`path_provider_foundation`]|-|2.2.1|2.2.1|
|[`path_provider_linux`]|-|2.1.10|2.1.10|
|[`path_provider_platform_interface`]|-|2.0.6|2.0.6|
|[`path_provider_windows`]|-|2.1.5|2.1.5|
|[`platform`]|-|3.1.0|3.1.0|
|[`plugin_platform_interface`]|-|2.1.4|2.1.4|
|[`process`]|-|4.2.4|4.2.4|
|[`sky_engine`]|-|0.0.99|0.0.99|
|[`source_span`]|-|1.9.1|1.9.1|
|[`stream_channel`]|-|2.1.1|2.1.1|
|[`string_scanner`]|-|1.2.0|1.2.0|
|[`term_glyph`]|-|1.2.1|1.2.1|
|[`typed_data`]|-|1.3.1|1.3.1|
|[`universal_io`]|-|2.2.0|2.2.0|
|[`url_launcher`]|-|6.1.10|6.1.10|
|[`url_launcher_android`]|-|6.0.26|6.0.26|
|[`url_launcher_ios`]|-|6.1.3|6.1.3|
|[`url_launcher_linux`]|-|3.0.4|3.0.4|
|[`url_launcher_macos`]|-|3.0.4|3.0.4|
|[`url_launcher_platform_interface`]|-|2.1.2|2.1.2|
|[`url_launcher_web`]|-|2.0.16|2.0.16|
|[`url_launcher_windows`]|-|3.0.5|3.0.5|
|[`vector_math`]|-|2.1.4|2.1.4|
|[`win32`]|-|3.1.3|4.1.1|
|[`window_to_front`]|-|0.0.3|0.0.3|
|[`xdg_directories`]|-|1.0.0|1.0.0|
</details>

To reproduce run `dart pub outdated --no-dev-dependencies --up-to-date --no-dependency-overrides`.

[`cookie_jar`]: https://pub.dev/packages/cookie_jar
[`device_info_plus`]: https://pub.dev/packages/device_info_plus
[`flutter`]: https://pub.dev/packages/flutter
[`flutter_web_auth_2`]: https://pub.dev/packages/flutter_web_auth_2
[`http`]: https://pub.dev/packages/http
[`package_info_plus`]: https://pub.dev/packages/package_info_plus
[`path_provider`]: https://pub.dev/packages/path_provider
[`universal_html`]: https://pub.dev/packages/universal_html
[`web_socket_channel`]: https://pub.dev/packages/web_socket_channel
[`async`]: https://pub.dev/packages/async
[`characters`]: https://pub.dev/packages/characters
[`charcode`]: https://pub.dev/packages/charcode
[`collection`]: https://pub.dev/packages/collection
[`crypto`]: https://pub.dev/packages/crypto
[`csslib`]: https://pub.dev/packages/csslib
[`device_info_plus_platform_interface`]: https://pub.dev/packages/device_info_plus_platform_interface
[`ffi`]: https://pub.dev/packages/ffi
[`file`]: https://pub.dev/packages/file
[`flutter_web_auth_2_platform_interface`]: https://pub.dev/packages/flutter_web_auth_2_platform_interface
[`flutter_web_plugins`]: https://pub.dev/packages/flutter_web_plugins
[`html`]: https://pub.dev/packages/html
[`http_parser`]: https://pub.dev/packages/http_parser
[`js`]: https://pub.dev/packages/js
[`material_color_utilities`]: https://pub.dev/packages/material_color_utilities
[`meta`]: https://pub.dev/packages/meta
[`package_info_plus_platform_interface`]: https://pub.dev/packages/package_info_plus_platform_interface
[`path`]: https://pub.dev/packages/path
[`path_provider_android`]: https://pub.dev/packages/path_provider_android
[`path_provider_foundation`]: https://pub.dev/packages/path_provider_foundation
[`path_provider_linux`]: https://pub.dev/packages/path_provider_linux
[`path_provider_platform_interface`]: https://pub.dev/packages/path_provider_platform_interface
[`path_provider_windows`]: https://pub.dev/packages/path_provider_windows
[`platform`]: https://pub.dev/packages/platform
[`plugin_platform_interface`]: https://pub.dev/packages/plugin_platform_interface
[`process`]: https://pub.dev/packages/process
[`sky_engine`]: https://pub.dev/packages/sky_engine
[`source_span`]: https://pub.dev/packages/source_span
[`stream_channel`]: https://pub.dev/packages/stream_channel
[`string_scanner`]: https://pub.dev/packages/string_scanner
[`term_glyph`]: https://pub.dev/packages/term_glyph
[`typed_data`]: https://pub.dev/packages/typed_data
[`universal_io`]: https://pub.dev/packages/universal_io
[`url_launcher`]: https://pub.dev/packages/url_launcher
[`url_launcher_android`]: https://pub.dev/packages/url_launcher_android
[`url_launcher_ios`]: https://pub.dev/packages/url_launcher_ios
[`url_launcher_linux`]: https://pub.dev/packages/url_launcher_linux
[`url_launcher_macos`]: https://pub.dev/packages/url_launcher_macos
[`url_launcher_platform_interface`]: https://pub.dev/packages/url_launcher_platform_interface
[`url_launcher_web`]: https://pub.dev/packages/url_launcher_web
[`url_launcher_windows`]: https://pub.dev/packages/url_launcher_windows
[`vector_math`]: https://pub.dev/packages/vector_math
[`win32`]: https://pub.dev/packages/win32
[`window_to_front`]: https://pub.dev/packages/window_to_front
[`xdg_directories`]: https://pub.dev/packages/xdg_directories

<details>
<summary>
The constraint `^3.0.1` on cookie_jar does not support the stable version `4.0.0`, that was published 8 days ago. 

 When cookie_jar is 30 days old, this package will no longer be awarded points in this category.
</summary>

Try running `dart pub upgrade --major-versions cookie_jar` to update the constraint.
</details>

### [*] 10/10 points: Package supports latest stable Dart and Flutter SDKs


## ✓ Support sound null safety (20 / 20)
### [*] 20/20 points: Package and dependencies are fully migrated to null safety!


Points: 100/130.

**Comment by lohanidamodar** [comment]
@stnguyen90 The details shows something to do with Flutter Web Auth 2 Package, linux support. However the package itself shows web support, so I'll look if updating to latest version resolves the issue
<img width="800" alt="image" src="https://user-images.githubusercontent.com/6360216/229324140-05fa6787-2774-4b82-9e70-8413d5f796d2.png">
