### ISSUE TITLE
🚀 Feature: Add Support to YugabyteDB

### ISSUE THREAD

**Issue by vaishakhpj** [appwrite/sdk-for-flutter#140]
### 🔖 Feature description

Hi, Please Add support to YugabyteDB because it can be scaled very easily and it is cloud native and also postgres compatible.

### 🎤 Pitch

YugabyteDB is Distributed SQL Database and it is a replacement for postgres db , it is cloud native so can be used in docker and scaled up or down according to the usage. It can be scaled to a very high transactions per second, so it will be easier to scale the appwrite system. Also it is open source.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by lohanidamodar** [comment]
@vaishakhpj I think this issue should be in https://github.com/appwrite/appwrite

**Comment by vaishakhpj** [comment]
Ok Thank you, will be posting there.

**Comment by stnguyen90** [comment]
Closing as a duplicate of https://github.com/appwrite/appwrite/issues/5412
