### ISSUE TITLE
🐛 Bug Report: Empty teams preferences returns list instead of map

### ISSUE THREAD

**Issue by lucasbstn** [appwrite/sdk-for-flutter#141]
### 👟 Reproduction steps

Fetch a team by ID where the team has empty preferences. 

### 👍 Expected behavior

After upgrading to Appwrite 1.3, an error is thrown when fetching teams by id or teams preferences. 
It seems that an empty list is returned when the preferences are empty. (See this [commit](https://github.com/appwrite/appwrite/commit/34d27fb4d0e74b31e334b0a8618ab70efd2a8858))

However if you look at the models defined in this package, the preferences is of type Map<String, dynamic>

### 👎 Actual Behavior

Throws an error:
type 'List<dynamic>' is not a subtype of type 'Map<String, dynamic>
stackTrace: #0      new Team.fromMap (package:appwrite/src/models/team.dart:39:37)
#1      Teams.get (package:appwrite/services/teams.dart:75:24)

### 🎲 Appwrite version

Version 2.0.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by joeyouss** [comment]
Related issue [#5361](https://github.com/appwrite/appwrite/pull/5361)

**Comment by joeyouss** [comment]
Related issue [#5365](https://github.com/appwrite/appwrite/issues/5365)
