### ISSUE TITLE
🐛 Bug Report:  macOS Flutter version 3.10.0  [!] CocoaPods could not find compatible versions for pod "flutter_web_auth_2": 

### ISSUE THREAD

**Issue by makao007** [appwrite/sdk-for-flutter#147]
### 👟 Reproduction steps

add dependencies in pubspec.yaml file
appwrite: ^9.0.0

### 👍 Expected behavior

flutter run -d macos  
launch success

### 👎 Actual Behavior

    Resolving dependencies of `Podfile`
      CDN: trunk Relative path: CocoaPods-version.yml exists! Returning local because checking is only performed in repo
      update
    [!] CocoaPods could not find compatible versions for pod "flutter_web_auth_2":
      In Podfile:
        flutter_web_auth_2 (from `Flutter/ephemeral/.symlinks/plugins/flutter_web_auth_2/macos`)

    Specs satisfying the `flutter_web_auth_2 (from `Flutter/ephemeral/.symlinks/plugins/flutter_web_auth_2/macos`)`
    dependency were found, but they required a higher minimum deployment target.

### 🎲 Appwrite version

Version 2.0.x

### 💻 Operating system

macOS 12.6.5 

### 🧱 Your Environment

Flutter 3.10.0
Dart SDK version: 3.0.0
macOS 12.6.5 

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by AriDevC** [comment]
Had to downgrade back to 3.7.12!

**Comment by lohanidamodar** [comment]
@makao007 Thanks for raising the issue.
As you can see from the error here `Specs satisfying the `flutter_web_auth_2 (from `Flutter/ephemeral/.symlinks/plugins/flutter_web_auth_2/macos`)`
dependency were found, but they required a higher minimum deployment target.` you need higher minimum deployment target. For macOS 10.15+ is required. I'll make sure we update the SDK readme and documentation to mention this.

**Comment by lohanidamodar** [comment]
This is just a version requirement mismatch. Which is now also mentioned in our [Appwrite for Flutter official guide](https://appwrite.io/docs/getting-started-for-flutter).
