### ISSUE TITLE
🐛 Bug Report:  PathNotFoundException: Cannot open file, path = '/etc/lsb-release'

### ISSUE THREAD

**Issue by romulka** [appwrite/sdk-for-flutter#151]
### 👟 Reproduction steps

Hello.

After update to new version (9.0.0)
After start app, got unhandled exception:

PathNotFoundException (PathNotFoundException: Cannot open file, path = '/etc/lsb-release' (OS Error: Нет такого файла или каталога, errno = 2))

Run on linux fedora 38.

I think problem with device_info_plus: 8.1.0 (maybe update will help).

### 👍 Expected behavior

No unhandled errors

### 👎 Actual Behavior

Got PathNotFoundException exception.

### 🎲 Appwrite version

Version 2.0.x

### 💻 Operating system

Linux

### 🧱 Your Environment

Fedora 38

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by lohanidamodar** [comment]
@romulka Thank you for reporting the problem. Will look into it further.

Regarding the device_info_plus plugin I don't see any error report regarding this error though.

I would appreciate your confirmation, if you could simply make a new Flutter project and test both device_info_plus 8.1.0 and latest in your new project for your system, to make sure it works.

**Comment by lohanidamodar** [comment]
@romulka please provide further information. Also with appwrite 9.0.1 latest release we are using latest version of device_info_plus. Let us know if the issue still persist.

**Comment by romulka** [comment]
Hello. Sorry, i don't have enough time to check you first answer (((

I updated to 9.0.1 and everything is fine! No unexpected errors. Thanks!
