### ISSUE TITLE
📚 Documentation: library code does not contain clear and or concise documentation

### ISSUE THREAD

**Issue by folaoluwafemi** [appwrite/sdk-for-flutter#152]
### 💭 Description

Basically the docs from the appwrite.io/docs page are clear, but I expect more finer grained docs from the flutter/dart sdk code to make it much more easier to understand what to do, let me paint a scenario.

* I create a project
* I import appwrite lib in my `main.dart` file.
* while initializing the `Client` class [from appwrite lib] I see a param `selfSigned` and ask myself what it means
  * I attempt a shortcut (`ctrl + j` on AS or Intellij) to show info from the added documentation, and nothing that can help my situation comes up
  * Confused, I click to go to the declaration to see if there's any helpful info, but alas!!!, there was none.
  *  At the last, I had to resolve to opening my browser to get info from the official docs.

My point? it would have been incredibly helpful to have the docs from the appwrite lib, even if it's just the public facing part of the lib.

Thank you.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by lohanidamodar** [comment]
@folaoluwafemi Thank you for your suggestion. We will work on it.

**Comment by stnguyen90** [comment]
Whoever works on this can refer to the SDK for web or node to see what the comment docs should be.

**Comment by iswarmondal** [comment]
Hey, @stnguyen90 @lohanidamodar  I'm new to Appwrite community. I just saw this issue and can contribute to clarifying the docs. May I give it a go?

**Comment by gewenyu99** [comment]
> Hey, @stnguyen90 @lohanidamodar I'm new to Appwrite community. I just saw this issue and can contribute to clarifying the docs. May I give it a go?

This isn't really a docs issue, this is a SDK generator issue I think, right @stnguyen90?

But this does sound like a good idea, I believe we brought this up during Hacktoberfest last year?

**Comment by gewenyu99** [comment]
> So what can we do to solve this? I really don't know what you are talking about @gewenyu99

We would have to make changes to the SDK Generator.

**Comment by stnguyen90** [comment]
@iswarmondal, for example, files like these:

* [id.dart](https://github.com/appwrite/sdk-generator/blob/master/templates/dart/lib/id.dart.twig)
* [query.dart](https://github.com/appwrite/sdk-generator/blob/master/templates/dart/lib/query.dart.twig)
* [client_io.dart ](https://github.com/appwrite/sdk-generator/blob/master/templates/flutter/lib/src/client_io.dart.twig)

would need to be updated.

**Comment by iswarmondal** [comment]
@stnguyen90 thanks mate, 🙌🏼
I'm trying to implement some changes, will create a PR after that

**Comment by stnguyen90** [comment]
@iswarmondal, actually, we need to update this ASAP, so I think we're going to work on it internally.

**Comment by iswarmondal** [comment]
@stnguyen90 no problem, I'm happy to interact with you guys

**Comment by lohanidamodar** [comment]
@folaoluwafemi With new version 9.0.1 this issue should be resolved. We have tried to cover all public functions. Feel free to reopen the issue if you think there's still things missing.
