### ISSUE TITLE
Unnecessary Overhead: the init() method

### ISSUE THREAD

**Issue by ryanhlewis** [appwrite/sdk-for-flutter#16]
Been looking through the SDK to write a client-dotnet twig, and I cannot wrap my head around the Flutter init() method. It is clearly to get cookies and set them within the CookieJar, and it turns itself off after it is bool initialized. 

I do not see the purpose of calling this in EVERY CALL() method.

There is no reason to. The only cookie necessary is a Login Cookie, and I solved this problem in Dotnet by putting the Cookie code in the initial Client() constructor (to attach the CookieJar) and in the Login Method itself (to add the proper cookie). The init() flutter code WORKS, but it is terrible etiquette. Once the variable has been set to false, which invariably it has after the program finds that one necessary cookie, it continues to call an empty method for EVERY Call() event ever.

It is bad code smell especially when it introduces the overhead of unnecessarily checking every Call() event for a true/false condition that is surely not going to change unless the user explicitly logs out, and even then, the Login method is still the best place for this kind of Cookie set.

**Comment by eldadfux** [comment]
I think this is legacy leftover from another behavior we used to have. Not sure exactly, but probably something to do with the OAuth2 integration. @lohanidamodar any reason why we should not move the first init call to the client constructor?

**Comment by TorstenDittmann** [comment]
@lohanidamodar is this issue still relevant?
