### ISSUE TITLE
🐛 Bug Report: '_Map<String, dynamic>' is not a subtype of type 'List<dynamic>' with permissions in a document

### ISSUE THREAD

**Issue by ande4485** [appwrite/sdk-for-flutter#162]
### 👟 Reproduction steps

1. create a document in a collection with permissions 

 ```dart
 adPanelUserDatabase.createDocument(
        databaseId: databaseId,
        collectionId: collectionAdPanelUser,
        documentId: appUser.idDatabase!,
        data: appUser.toJson(),
        permissions: [
          Permission.write(Role.user(appUser.idDatabase!)),
          Permission.update(Role.user(appUser.idDatabase!)),
          Permission.read(Role.users()),
          Permission.delete(Role.user(appUser.idDatabase!))
        ]);
```

2. After make an getDocument:

```dart
 await adPanelUserDatabase.getDocument(
          databaseId: databaseId,
          collectionId: collectionAdPanelUser,
          documentId: idUser);
```
### 👍 Expected behavior

No error throws

### 👎 Actual Behavior

I got '_Map<String, dynamic>' is not a subtype of type 'List<dynamic>' , because in this line :

```dart
factory Document.fromMap(Map<String, dynamic> map) {
    return Document(
      $id: map['\$id'].toString(),
      $collectionId: map['\$collectionId'].toString(),
      $databaseId: map['\$databaseId'].toString(),
      $createdAt: map['\$createdAt'].toString(),
      $updatedAt: map['\$updatedAt'].toString(),
      $permissions: map['\$permissions'],
      data: map,
    );
  }
```
Line 41 in document.dart
$permissions are a List<dynamic> but map['$permissions'] are a map.

### 🎲 Appwrite version

Different version (specify in environment)

### 💻 Operating system

Linux

### 🧱 Your Environment

Flutter appwrite 9.0.1.
Flutter 3.10.6
Appwrite Cloud

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by lohanidamodar** [comment]
@ande4485 With Appwrite cloud, it's recommended to use Flutter Appwrite SDK 8.x.x instead of 9.x.x

Let us know if using 8.x.x solves the issue?

**Comment by ande4485** [comment]
@lohanidamodar , thank you for your message, but even with appwrite: ^8.3.0 I have always this error. 
If I test with latest version with appwrite on Docker and with flutter pub appwrite: 9.x.x, I have no problem.

**Comment by stnguyen90** [comment]
@ande4485, you're probably facing https://github.com/appwrite/appwrite/issues/5661 beacuse of duplicate permissions:

```dart
         Permission.write(Role.user(appUser.idDatabase!)),
         Permission.update(Role.user(appUser.idDatabase!)),
         Permission.read(Role.users()),
         Permission.delete(Role.user(appUser.idDatabase!))
```

because write is an alias for update + delete. So, you should just do:

```dart
         Permission.write(Role.user(appUser.idDatabase!)),
         Permission.read(Role.users())
```
