### ISSUE TITLE
🐛 Bug Report:  Teams API - create/list methods throwing type conversion errors because of null value

### ISSUE THREAD

**Issue by jemish54** [appwrite/sdk-for-flutter#163]
### 👟 Reproduction steps

Type Conversion Error because of Cloud beta version does not have property Prefs in Team Model.

- Create / List methods of Teams API giving:
  null is not a subtype of Map<String,dynamic>.

### 👍 Expected behavior

It should work with Cloud Beta Appwrite version even if it doesn't contain Preference object inside Team Model. 

As Appwrite cloud will be upgraded to version 1.3.x ,This issue will not persist as Preference Object will be added.

Till Then please consider this as it will be a very quick issue to fix.

### 👎 Actual Behavior

create team is working (As i can see Team getting added on Appwrite Dashboard) but throwing error

List method will always throw Type conversion error because of null value of Preferences.

### 🎲 Appwrite version

Version 1.0.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by lohanidamodar** [comment]
For Appwrite cloud please use Flutter Appwrite SDK version 8.x.x not 9.x.x and that should solve your issue.
