### ISSUE TITLE
Help me fixing this

### ISSUE THREAD

**Issue by MohamedKamran** [appwrite/sdk-for-flutter#166]
flutter: AppwriteException: , Failed host lookup: 'api.appwrite.io' (0)

Can somebody help me

**Comment by MohamedKamran** [comment]
Ummm...
It's Actually having problem in:
1. MacBook (M1) App
2. iOS app too
3. Android

Ig it's related to some INTERNET permissions but I have no idea.
I'll be greatful if somebody assists me

**Comment by stnguyen90** [comment]
> flutter: AppwriteException: , Failed host lookup: 'api.appwrite.io' (0)
> 
> Can somebody help me

@MohamedKamran, `api.appwrite.io` is not a valid domain. If you need additional help, feel free to join us on [Discord](https://appwrite.io/discord/).
