### ISSUE TITLE
🐛 Bug Report: Flutter App fails to build after adding aappwrite^10.0.0 as dependency

### ISSUE THREAD

**Issue by Rohit-RA-2020** [appwrite/sdk-for-flutter#171]
### 👟 Reproduction steps

Running the Flutter App after installing **appwrite^10.0.0** gives a build time error. 

Error Says:
`Error: Can't declare 'headers' because it was already used in this scope.`

![Screenshot 2023-09-01 123121](https://github.com/appwrite/sdk-for-flutter/assets/53489549/3371c597-07e9-4b5d-9f49-56948a93d580)

### 👍 Expected behavior

Should build without any errors

### 👎 Actual Behavior

App fails to build

### 🎲 Appwrite version

Version 2.0.x

### 💻 Operating system

Windows

### 🧱 Your Environment

Flutter v3.13.0 on Windows, building for Android

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by istornz** [comment]
Same error on my end...
Trying to `flutter clean` but nothing...

**Comment by AmHughesAbsalom** [comment]
Here is how i sovled it in Windows:
1.first navigate to this file and ensure you've checked the "Hidden items" to access the "AppData" folder.
(C:\Users\"Your Desktop name"\AppData\Local\Pub\Cache\hosted\pub.dev\appwrite-10.0.0\lib\services).

2.Then change the variable names of "headers" in "listExecution", "createExecution" and "getExecution" functions to unique names, as i have done in my code below:

part of appwrite;

/// The Functions Service allows you view, create and manage your Cloud
/// Functions.
class Functions extends Service {
  /// Initializes a [Functions] service
  Functions(super.client);

  /// List Executions
  ///
  /// Get a list of all the current user function execution logs. You can use the
  /// query params to filter your results.
  Future<models.ExecutionList> listExecutions(
      {required String functionId,
      List<String>? queries,
      String? search}) async {
    final String apiPath = '/functions/{functionId}/executions'
        .replaceAll('{functionId}', functionId);

    final Map<String, dynamic> params = {
      'queries': queries,
      'search': search,
    };

    final Map<String, String> listExecutionsHeaders = {
      'content-type': 'application/json',
    };

    final res = await client.call(HttpMethod.get,
        path: apiPath, params: params, headers: listExecutionsHeaders);

    return models.ExecutionList.fromMap(res.data);
  }

  /// Create Execution
  ///
  /// Trigger a function execution. The returned object will return you the
  /// current execution status. You can ping the `Get Execution` endpoint to get
  /// updates on the current execution status. Once this endpoint is called, your
  /// function execution process will start asynchronously.
  Future<models.Execution> createExecution(
      {required String functionId,
      String? body,
      bool? xasync,
      String? path,
      String? method,
      Map? headers}) async {
    final String apiPath = '/functions/{functionId}/executions'
        .replaceAll('{functionId}', functionId);

    final Map<String, dynamic> params = {
      'body': body,
      'async': xasync,
      'path': path,
      'method': method,
      'headers': headers,
    };

    final Map<String, String> createExecutionHeaders = {
      'content-type': 'application/json',
    };

    final res = await client.call(HttpMethod.post,
        path: apiPath, params: params, headers: createExecutionHeaders);

    return models.Execution.fromMap(res.data);
  }

  /// Get Execution
  ///
  /// Get a function execution log by its unique ID.
  Future<models.Execution> getExecution(
      {required String functionId, required String executionId}) async {
    final String apiPath = '/functions/{functionId}/executions/{executionId}'
        .replaceAll('{functionId}', functionId)
        .replaceAll('{executionId}', executionId);

    final Map<String, dynamic> params = {};

    final Map<String, String> getExecutionHeaders = {
      'content-type': 'application/json',
    };

    final res = await client.call(HttpMethod.get,
        path: apiPath, params: params, headers: getExecutionHeaders);

    return models.Execution.fromMap(res.data);
  }
}

**Comment by lohanidamodar** [comment]
@Rohit-RA-2020 @istornz This issue should be fixed with version `10.0.1` please confirm. Thank you.

**Comment by Rohit-RA-2020** [comment]
Closing this issue as this has been fixed in `10.0.1`
