### ISSUE TITLE
🐛 Bug Report: Unhandled Exception: type 'Null' is not a subtype of type 'List<dynamic>'

### ISSUE THREAD

**Issue by jtmuller5** [appwrite/sdk-for-flutter#173]
### 👟 Reproduction steps

I see an error when trying to create a new account:

```
E/flutter (14287): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: type 'Null' is not a subtype of type 'List<dynamic>'
E/flutter (14287): #0      new User.fromMap (package:appwrite/src/models/user.dart:87:18)
E/flutter (14287): #1      Account.create (package:appwrite/services/account.dart:57:24)
E/flutter (14287): <asynchronous suspension>
E/flutter (14287): #2      AppwriteService.createEmailAccount (package:appwrite_auth_ui/src/components/services/appwrite_service.dart:81:19)
E/flutter (14287): <asynchronous suspension>
E/flutter (14287): #3      AppwriteSignupState.onSignup (package:appwrite_auth_ui/src/components/screens/signup/signup.dart:29:43)
E/flutter (14287): <asynchronous suspension>
E/flutter (14287): 
```

Apparently the "labels" property is required in the User model but its not returned by the create() method.

### 👍 Expected behavior

Don't require the labels property on the User model or return the labels list in the create response.

### 👎 Actual Behavior

An error is thrown

### 🎲 Appwrite version

Version 2.0.x

### 💻 Operating system

MacOS

### 🧱 Your Environment

Basic Flutter app in Android studio. Running on emulator

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@jtmuller5, thanks for creating this issue! 🙏🏼 What version of Appwrite are you on?

**Comment by jtmuller5** [comment]
Hi, I am using version 11.0.0 of the appwrite package on pub dev. I haven't made any other changes to my appwrite setup.

**Comment by stnguyen90** [comment]
@jtmuller5 Sorry, I meant what version of the Appwrite server?

**Comment by jtmuller5** [comment]
It looks like the project is using v 1.1.2. I set it up using the "Get Started" button in Appwrite cloud. Is there a way to upgrade this?

**Comment by FaisalMohammadi** [comment]
i have the same issue when i try to do Query.Select in listDocuments.
I am using flutter sdk 11.0.1 and my appwrite instance is 1.4.11

**Comment by Weav3r** [comment]
Same issue.
sdk: 11.0.1
appwrite: 1.4.13

It works for a single document i.e `db.getDocument(...)`
P.S. cli works, rest works and apparently graphql also works

**Comment by iaggocapitanio1** [comment]
having the same issue, is a problem in the serialization processs, the labels field in the creation is null but it's defines as List .
