### ISSUE TITLE
🐛 Bug Report: Upgrade http library to latest stable

### ISSUE THREAD

**Issue by istornz** [appwrite/sdk-for-flutter#179]
### 👟 Reproduction steps

More and more other dependency upgrade http to latest stable version, we can't upgrade others dependencies since this library depends on `'>=0.13.6 <1.0.1'`, example with basic_utils v5.7.0 (latest).

```
Because basic_utils >=5.6.1 depends on http ^1.1.0 and appwrite 11.0.0 depends on http >=0.13.6 <1.0.1, basic_utils >=5.6.1 is incompatible with appwrite 11.0.0.
And because no versions of appwrite match >11.0.0 <12.0.0, basic_utils >=5.6.1 is incompatible with appwrite ^11.0.0.
So, because dart_rss depends on both appwrite ^11.0.0 and basic_utils ^5.7.0, version solving failed.
```

Thanks :

### 👍 Expected behavior

It should use latest stable http version

### 👎 Actual Behavior

It use version `'>=0.13.6 <1.0.1'` of http package

### 🎲 Appwrite version

Version 2.0.x

### 💻 Operating system

MacOS

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by furkanbora239** [comment]
[use this](https://github.com/furkanbora239/sdk-for-flutter)

I have same problem so i just fork his stomic and change http package then pull his stomic again now its working fine for me.

use client like this btw.

static Client client =
      Client(endPoint: 'https://cloud.appwrite.io/v1', selfSigned: true)
          .setProject('-----------your key------');
  Account account = Account(client);

**Comment by lohanidamodar** [comment]
@istornz Thank you for reporting the issue. Will update soon.

**Comment by mark-at-pieces** [comment]
Also experiencing the same issue with the dart SDK as well

https://github.com/appwrite/sdk-for-dart

**Comment by agabeyre** [comment]
Same issue with dart sdk here too.  I cannot Flutter Quil Extensions package as it requires http 1.0.0 package while Appwrite Dart SDK package uses http 0.13 so I am getting this error when calling pub get:
_Because flutter_quill_extensions >=0.5.0 depends on http ^1.1.0 and appwrite 11.0.1 depends on http >=0.13.6 <1.0.1, flutter_quill_extensions >=0.5.0 is incompatible with appwrite 11.0.1._

Is anyone from Appwrite team resolving this issue?  Flutter Quil is a popular text editor for Flutter and the Flutter Quil Extensions allows inserting images and attachments to the edited documents.  It is Appwrite or the editor for me now and that is a tough choice really.

**Comment by istornz** [comment]
I think, as a workaround, we can override `http` version in the `pubpec.yaml` but this issue need to be fixed ASAP thanks 👍

**Comment by agabeyre** [comment]
Thanks for the suggestion.  I have pointed to a forked git version in the
pubspec and that resolved this issue.  But I want to stay with the master
Apprite SDK so I can sync any new features when the package gets a new
version from the Appwrite team.

**Comment by istornz** [comment]
Hi @lohanidamodar, do you have any news about this issue? 👍

**Comment by stnguyen90** [comment]
Related to https://github.com/appwrite/sdk-for-dart/issues/59
