### ISSUE TITLE
I want to contribute

### ISSUE THREAD

**Issue by ishanvaghani** [appwrite/sdk-for-flutter#186]
Recently, I started making open-source contributions. I made some contributions to Flutter and Android apps. Now I want to make a contribution to some libraries. I have used Appwrite personally for one of my Flutter projects, so it will be great if I can contribute to this library. Let me know if there is anything for me (bug fix, feature, improvement, or unit test).

**Comment by stnguyen90** [comment]
Welcome! Make sure to check out https://github.com/appwrite/appwrite/discussions/4899
