### ISSUE TITLE
401 error and missing scope when run playground-for-flutter

### ISSUE THREAD

**Issue by helloabook** [appwrite/sdk-for-flutter#19]
```
browser_adapter.dart:98 GET https://localhost/v1/account 401
js_primitives.dart:30  User (role: guest) missing scope (account)
```
Code is from:  https://github.com/appwrite/playground-for-flutter. And I comment out the addHeader line:
```
client          .setEndpoint(              'https://localhost/v1')
 // Make sure your endpoint is accessible from your emulator, use IP if needed         
.setProject('60793ca4ce59e') // Your project ID          
.setSelfSigned() // Do not use this in production         
//.addHeader('Origin', 'http://localhost') ;
```
BTW, sdk for node works.

**Comment by lohanidamodar** [comment]
> ```
> browser_adapter.dart:98 GET https://localhost/v1/account 401
> js_primitives.dart:30  User (role: guest) missing scope (account)
> ```
> 
> Code is from: https://github.com/appwrite/playground-for-flutter. And I comment out the addHeader line:
> 
> ```
> client          .setEndpoint(              'https://localhost/v1')
>  // Make sure your endpoint is accessible from your emulator, use IP if needed         
> .setProject('60793ca4ce59e') // Your project ID          
> .setSelfSigned() // Do not use this in production         
> //.addHeader('Origin', 'http://localhost') ;
> ```
> 
> BTW, sdk for node works.

Please describe the scenario you are getting the error? What are you trying to do? Are you logged in? and Error possibly displayed in the browsers console looks like you are running on web?

**Comment by lohanidamodar** [comment]
Closing as there was no further response. Feel free to reopen if you have further issues.
