### ISSUE TITLE
Port # seems to be ignored

### ISSUE THREAD

**Issue by mmcdon20** [appwrite/sdk-for-flutter#2]
I initialize the client endpoint to localhost with a given port.
```dart
  final Client _client = Client()
      .setEndpoint('http://localhost:8089/v1')
      .setProject(projectId)
      .setSelfSigned(status: true);
```
But then when I make any request using the client I get the following error.
```
E/flutter ( 5606): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: DioError [DioErrorType.DEFAULT]: SocketException: OS Error: Connection refused, errno = 111, address = localhost, port = 59488
```
The port number in the error message changes every time a request is made. 
Is there some other way of specifying the port number?

**Comment by eldadfux** [comment]
Can you check if your emulator can access the Appwrite console from your emulator browser? http://localhost:8089/console

**Comment by mmcdon20** [comment]
![Android Emulator - Pixel_2_API_28_5554 5_23_2020 11_18_28 PM](https://user-images.githubusercontent.com/5104543/82745589-d92e0000-9d4b-11ea-9c62-9bc2a976e73e.png)
No, but you pointed me in the right direction. I changed 'http://localhost:8089/v1' to 'http://10.0.2.2:8089/v1'. And it now appears to be working.
