### ISSUE TITLE
🐛 Bug Report: Compile error in 13.0.0-rc.2

### ISSUE THREAD

**Issue by svenopdehipt** [appwrite/sdk-for-flutter#216]
### 👟 Reproduction steps

Try to compile the app while including appwrite version 13.0.0-rc.2

### 👍 Expected behavior

Compiles correctly

### 👎 Actual Behavior

Throws the following error while compiling:
```
../../../.pub-cache/hosted/pub.dev/appwrite-13.0.0-rc.2/lib/services/functions.dart:141:18: Error: The getter 'paramName' isn't defined for the class 'Functions'.
 - 'Functions' is from 'package:appwrite/appwrite.dart' ('../../../.pub-cache/hosted/pub.dev/appwrite-13.0.0-rc.2/lib/appwrite.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'paramName'.
      paramName: paramName,
                 ^^^^^^^^^
Failed to compile application.
```

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
13.0.0 doesn't have this problem and we'll make sure this is addressed when we add multipart form support.
