### ISSUE TITLE
Null pointer in `createOAuth2Session`

### ISSUE THREAD

**Issue by JulianBissekkou** [appwrite/sdk-for-flutter#23]
When calling `createOAuth2Session` in the Flutter SDK, the method crashes if `success` or `failure` is null which is allowed since both params are optional.

Here is the line and a potential fix:

```dart

    params.forEach((key, value) {
      if (value is List) {
        for (var item in value) {
          query.add(Uri.encodeComponent(key + '[]') +
              '=' +
              Uri.encodeComponent(item));
        }
      } else if(value != null) { // null check fixes the crash.
        // can not parse null value into a Uri.
        query.add(Uri.encodeComponent(key) + '=' + Uri.encodeComponent(value));
      }
    });
```

I would love to provide a PR that fixes this issue, but i am not sure if i can just fork the repo. Don't you generate the dart code?

@TorstenDittmann

**Comment by JulianBissekkou** [comment]
As an addition I would also propose to add more type information to the method signature:

```dart
  Future<void> createOAuth2Session(
      {required String provider,
      String? success,
      String? failure,
      List<String>? scopes,
      })
```

**Comment by lohanidamodar** [comment]
@JulianBissekkou Thank you for reporting the issue, we have worked the fix and is waiting release
https://github.com/appwrite/sdk-generator/pull/220
