### ISSUE TITLE
Potential crash in `Client.call`

### ISSUE THREAD

**Issue by JulianBissekkou** [appwrite/sdk-for-flutter#24]
We are using some new app write APIs that are not yet documented. In this case, we are using the `Client` to access the Rest Endpoints.
This is obviously more of a "power" user thing, but I thought it might be good to mention it.

The `Client.call` will crash if the provided `params` or `headers` are empty.

```dart
Future<Response> call(HttpMethod method,
      {String path = '',
      Map<String, String> headers = const {},
      Map<String, dynamic> params = const {},
      ResponseType? responseType,
})
```

The problem is that `const {}` will create unmodifiable maps which will result in a crash. 
For example `params.removeWhere((key, value) => value == null);` a few lines after.

Some other code is working around that for example `createJwt` which creates an empty but not `const` map.

```dart
  Future<Response> createJWT() {
    final String path = '/account/jwt';

    final Map<String, dynamic> params = {};

    final Map<String, String> headers = {
      'content-type': 'application/json',
    };

    return client.call(HttpMethod.post,
        path: path, params: params, headers: headers);
  }
```

This could be reduced to this:

```dart
  Future<Response> createJWT() {
   return client.call(HttpMethod.post, path: '/account/jwt', headers: { 'content-type': 'application/json' });
  }
```

**Comment by lohanidamodar** [comment]
@JulianBissekkou is it the only line that causes crash? 
https://github.com/appwrite/sdk-generator/pull/220
on this I have also added isEmpty check for params before trying to remove null params

**Comment by JulianBissekkou** [comment]
The same could happen with `headers` so it makes sense to catch this as well. (Basically any map that is initialized with `const {}`)

Another edge case is if someone does something like this: `client.call(headers: Map.unmodifiable({"stuff": "stuff"}))`.
Here the user passes an unmodifiable map into the `call` method. Your implementation would still crash here.
But instead of checking if it's empty, I would just create a copy of the Map. This way you can make sure that it's modifiable 👍🏽 

But you can decide if you want to handle this. I would understand if an API requires a `Map` to be modifiable.
If you want to support this as well you can use `final updatedHeaders = Map.of(headers)..removeWhere((x) => x != null)`

**Comment by TorstenDittmann** [comment]
This should be fixed with the release of Flutter SDK version 0.7.1 👍🏻

**Comment by JulianBissekkou** [comment]
Good job! Checked out the fix and it works.
