### ISSUE TITLE
FormatException: Invalid HTTP header field value: "中文字符/1.0.0 (Linux; U; Android 9; samsung SM-G950F)" (at character 1)

### ISSUE THREAD

**Issue by kutear** [appwrite/sdk-for-flutter#25]
ref: https://github.com/dart-lang/http/issues/227

`user-agent` containing a non English character is invalid like '中文字符(app_name)'.

**Comment by kutear** [comment]
I submit my fixed at https://github.com/appwrite/sdk-generator/pull/221

**Comment by TorstenDittmann** [comment]
@kutear is it fixed for you? 🙂

**Comment by kutear** [comment]
> @kutear is it fixed for you? 🙂

Yes, my submit had be merged. but still not publish a release version.  this issue can be closed when a new flutter package be published.

**Comment by lohanidamodar** [comment]
Hey @kutear please confirm that version 0.7.0 of the SDK fixes this for you. Thank you
https://pub.dev/packages/appwrite

**Comment by kutear** [comment]
> Hey @kutear please confirm that version 0.7.0 of the SDK fixes this for you. Thank you
> https://pub.dev/packages/appwrite

yes, this bug had be fixed at `0.7.0` and this issues should be closed.

**Comment by kutear** [comment]
GOD!  this fix had been rollback. now this issus can be reproduced at `1.0.2`
https://github.com/appwrite/sdk-for-flutter/blob/master/lib/src/client_io.dart#L155

**Comment by TorstenDittmann** [comment]
@kutear Oh, that is not good news. Sorry for the inconvenience 🙏🏻 

We have completely re-written the Flutter SDK for `1.0.0`, so this was probably overlooked. We will fix it as soon as @lohanidamodar is available.

**Comment by lohanidamodar** [comment]
@kutear Hey sorry for the inconvenience, I have a fix for it and will be released soon
https://github.com/appwrite/sdk-generator/pull/259

**Comment by TorstenDittmann** [comment]
@kutear We just released `1.0.3` with this fix included again 👍🏻 

https://github.com/appwrite/sdk-for-flutter/releases/tag/1.0.3

**Comment by lohanidamodar** [comment]
Feel free to reopen, if this occurs again.

**Comment by kutear** [comment]
> Feel free to reopen, if this occurs again.

https://github.com/appwrite/sdk-for-flutter/blob/1.0.3/lib/src/client_io.dart#L155

but i can see any modify at `1.0.3`, it's wrong to released?
