### ISSUE TITLE
AppwriteException: User (role: guest) missing scope (documents.write) (401) while creating new document

### ISSUE THREAD

**Issue by wrteam-priyansh** [appwrite/sdk-for-flutter#35]
Unable to add a document in the database. I have not authenticated the user.
Here is my code.

//
Client client = Client();
      client.setEndpoint(databaseUrl).setProject("6156deb490468").setSelfSigned(status: true);
      Database database = Database(client);
      database
          .createDocument(
            collectionId: '6156e69af2f61',
            data: {
              "name": "India",
              "capital": "Delhi",
            },
            write: ["*"],
            read: ["*"],
          )
          .then((value) => print(value.$id))
          .catchError((e) {
            print(e.toString());
          });
//

Am I missing something?

**Comment by lohanidamodar** [comment]
Hey @wrteam-priyansh the database write operation is not permitted for un-authenticated users. if you don't want to authenticate user with their details you can use anonymous session to authenticate then you should be able to insert document. Closing this issues as resolved. If you have problems even after authentication feel free to reopen this issue.

**Comment by ksmk007** [comment]
message: User (role: guest) missing scope (files.write), code: 401, version: 0.12.3
