### ISSUE TITLE
CERTIFICATE*VERIFY*FAILED: certificate has expired on Windows 10

### ISSUE THREAD

**Issue by EliasDeuss** [appwrite/sdk-for-flutter#37]
This is the error I get when trying to connect to my appwrite server. I have a valid SSL (When visiting the address on Chrome give no SSL issues).

I have all the .env settings at default except the domain and the require ssl.

`[ERROR:flutter/lib/ui/ui*dart*state.cc(199)] Unhandled Exception: AppwriteException: HandshakeException: Handshake error in client (OS Error:

 CERTIFICATE*VERIFY*FAILED: certificate has expired(../../third_party/boringssl/src/ssl/handshake.cc:359)) (0)`

Flutter doctor: 
`[√] Flutter (Channel stable, 2.5.1, on Microsoft Windows [Version 10.0.19043.1237], locale en-US)
    • Flutter version 2.5.1 at C:\Users\Elias\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ffb2ecea52 (2 weeks ago), 2021-09-17 15:26:33 -0400
    • Engine revision b3af521a05
    • Dart version 2.14.2
`

**Comment by lohanidamodar** [comment]
Can you make a request to your endpoint with `http` package instead and check if you get the same error? If yes, this might be `http` package issue not an issue with Appwrite's Flutter SDK.

**Comment by lohanidamodar** [comment]
@EliasDeuss Yes, they later reported that it was their system that was causing the issue. Can you verify if it's something related directly to Appwrite and not in general. If you could share the codes you used both the code with Appwrite SDK that's causing the error and code with http package directly that's working as expected I might be able to provide further assistance.
Thank you

**Comment by lohanidamodar** [comment]
Closing this as there are no new activity. Feel free to reopen if the issue still persist.
