### ISSUE TITLE
Add contains possibility for listdocuments

### ISSUE THREAD

**Issue by akram-95** [appwrite/sdk-for-flutter#38]
I want to check if a word comes in a text but I couldn't do that with actual filters functions 
Can you please implement that ?

**Comment by lohanidamodar** [comment]
@akram-95 I'm not sure I understand. Please describe more in details with examples and use cases. And most suitable place for this would be [Appwrite github discussions](https://github.com/appwrite/appwrite/discussions) so please continue there.
Thank you
