### ISSUE TITLE
How to get the url after a save an image on the storage API ?

### ISSUE THREAD

**Issue by akram-95** [appwrite/sdk-for-flutter#39]
I need the url after the store for viewing the image using Image.network

**Comment by lohanidamodar** [comment]
@akram-95 The image viewing with URL only works for images uploaded with public ('*') permission at the moment and you can construct that directly. For example a preview URL could be
`YOUR_ENDPOINT/storage/files/FILE_ID/preview?project=YOUR_PROJECT_ID&width=350&height=250`
