### ISSUE TITLE
📚 Documentation: 

### ISSUE THREAD

**Issue by pauli2406** [appwrite/sdk-for-flutter#40]
### 💭 Description

Hey,

How would I configure different appwrite projects  per flavor? (Development, Staging, Production)

For iOS it is simple by just providing a different project id when initializing the client.

Tho I am having issues with the android setup, where I need to additionally add the new activity with the project id as a key

is there some documentation available or if not could you provide me with some?

Best regards,
Marcel 

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by lohanidamodar** [comment]
@pauli2406 What you are saying for iOS by providing different project id should work for any other platform including Flutter.

You can setup different projects in your console and then in Flutter when you run different flavor switch the project ID during client initialization. You should also remember to handle Collection IDs if you are using those per flavor as they would be different.

Not sure if this answers what you are looking for. Please provide more details if this is not what you are looking for.
