### ISSUE TITLE
🐛 Bug Report: Realtime subscribe creates two websocket connections 

### ISSUE THREAD

**Issue by s3ppo** [appwrite/sdk-for-flutter#41]
### 👟 Reproduction steps

I use this code to connect:
```
class _MyChatPageState extends State<ChatPage> {
  AuthState? _state;
  late final Client client = Client();
  late final Realtime realtime;
  late final RealtimeSubscription _chat;
  final String chatCollectionId = "61346bcfbd96e";

  @override
  void initState() {
    super.initState();
    client.setEndpoint(Constants.endPoint).setProject(Constants.projectId);
    realtime = Realtime(client);
    subscribeChat();
  }

  @override
  void deactivate() {
    _chat.close();
    super.deactivate();
  }

  subscribeChat() {
    try {
      _chat = realtime.subscribe(['collections.$chatCollectionId.documents']);
    } on AppwriteException catch (error) {
      print(error.message);
    }
    _chat.stream.listen((data) {
      if (data.payload.isNotEmpty) {
        switch (data.event) {
          case "database.documents.create":
            print(data.payload);
            break;
          default:
            break;
        }
      }
    });
  }
}
```

i think it tries to create a reconnect after first connect.. the second one can be closed on dispose, but the first one can not be closed

<img width="257" alt="Bildschirmfoto 2021-10-18 um 14 37 13" src="https://user-images.githubusercontent.com/17125438/137731887-b8adebf0-36a5-4dc5-bd8c-3448dca92e8c.png">

<img width="257" alt="Bildschirmfoto 2021-10-18 um 14 38 19" src="https://user-images.githubusercontent.com/17125438/137732083-e3e60525-db7b-4224-9812-84d860564982.png">

### 👍 Expected behavior

1 connection for 1 subscribe :)

### 👎 Actual Behavior

2 connections for 1 subscribe :)

### 🎲 Appwrite version

Version 2.0.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by eldadfux** [comment]
@lohanidamodar any news on this one?

**Comment by s3ppo** [comment]
https://github.com/appwrite/sdk-generator/pull/314
