### ISSUE TITLE
🚀 Feature: Add SetKey method to Client class.

### ISSUE THREAD

**Issue by chrislaurie-bs** [appwrite/sdk-for-flutter#44]
### 🔖 Feature description

Currently, the SetKey method does not exist. It does in dart_appwrite.

### 🎤 Pitch

When trying to build an admin application that requires access to all artefacts outside the normal permissions, you need to be able to set the api key to use.  See: https://appwrite.io/docs/getting-started-for-server#apiKey

However, the SetKey method is not exposed in the flutter_appwrite package. it is in all the other libraries (nodejs etc).

I have tried to switch my app to use dart_appwrite, but then I loose the appwrite/models and session classes.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by lohanidamodar** [comment]
@chrislaurie-bs 
1. Adding and setting key on client side application is not secure
2. We have set-key on all server side SDKs only, that is why, `dart_appwrite` has it but `appwrite` doesn't have it. 
3. If you want to use both sessions and API keys, in client side, at your own risk, you can use both the packages together.
4. Regarding the response models, it's already ready for `dart_appwrite` SDK and we will be releasing soon

We still suggest not adding API key to client side applications, however if you are building the application for own self, not exposed to external users, you can implement both the SDKs together to achieve what you need.

Let me know if you have any further issues.

**Comment by eldadfux** [comment]
The new Dart SDK is now available: https://dev.to/appwrite/announcing-appwrite-dart-sdk-20-50a1
