### ISSUE TITLE
📚 Documentation: Using maps

### ISSUE THREAD

**Issue by jenniestrongbow** [appwrite/sdk-for-flutter#45]
### 💭 Description

Hi, is it possible to use Maps instead of arrays with the database? Thanks

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by lohanidamodar** [comment]
@jenniestrongbow having trouble to understand what you mean, please provide more details 🙏🏻

**Comment by lohanidamodar** [comment]
Closing this as no new information was provided. Feel free to reopen with proper information.
