### ISSUE TITLE
Useless Key and Secret check in Flutter Web

### ISSUE THREAD

**Issue by Mabenan** [appwrite/sdk-for-flutter#47]
This peace of coding looks a bit useless to my eyes it also makes problems. When you are following the Describition how to request OAuth it results in an error that Key and Secret is missing.

https://github.com/appwrite/sdk-for-flutter/blob/81d8453f62e55e557f40320225452d4fd26eabe1/lib/src/client_browser.dart#L152

**Comment by PineappleIOnic** [comment]
The `url` variable in this code snippet is very much needed as we need to be able to parse the URL Recieved back from the OAuth callback. As you can see here: https://github.com/appwrite/sdk-for-flutter/blob/81d8453f62e55e557f40320225452d4fd26eabe1/lib/src/client_browser.dart#L152-L154 `url` is used to get the Key and Secret to properly authenticate. If they are missing it is most likely another problem with how the OAuth provider has been configured. If you would like support I am more than happy to help you with your problem in our discord server. 🙂

**Comment by Mabenan** [comment]
yeah but key and secret is not used (in web for android it is a different thing). The Authentification works by the way if i go around the key and secret with the following success url http://localhost/auth.html?key=bla&secret=bla. So I don't thing it really has any use.

**Comment by PineappleIOnic** [comment]
@lohanidamodar Might be able to give a bit more insight about this than I can 🙂

**Comment by lohanidamodar** [comment]
@Mabenan as I see now, it does seem not required. Though it was not causing any issues when we last tested, we will surely update this. Thank you for notifying 🙏🏻

**Comment by Mabenan** [comment]
I've tested it. It works now. A Little confusing is that the return of the createOAuth2Session is now the success URL while it was all the time null. But I think thats ok.
