### ISSUE TITLE
🐛 Bug Report: account.get() throwing error as appwrite returns int instead of bool

### ISSUE THREAD

**Issue by jsownz** [appwrite/sdk-for-flutter#48]
### 👟 Reproduction steps

Flutter v.2.8.1
Dart v2.15.1
Appwrite v0.11.0.170

Create account
login:
`await account.createSession(email: email, password: password);`
call account.get:
`await account.get();`

```
E/flutter (30394): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: type 'int' is not a subtype of type 'bool'
E/flutter (30394): #0      new User.fromMap (package:appwrite/src/models/user.dart:45:18)
E/flutter (30394): #1      Account.get (package:appwrite/services/account.dart:21:24)
```

Can be solved by modifying `\lib\src\models\user.dart:45` to:
`status: map['status']== 0 ? false : true,`

### 👍 Expected behavior

Return the user data

### 👎 Actual Behavior

throws type error

### 🎲 Appwrite version

Different version (specify in environment)

### 💻 Operating system

Linux

### 🧱 Your Environment

Running manual docker config (needed different ports)

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by Meldiron** [comment]
In Appwrite 0.11, we used integer status values `0,1,2`. In Appwrite 0.12 this has been replaced with boolean values `true/false`. Can you double-check if you are using the correct SDK version for your Apwrite server?

If you use Appwrite 0.12, the latest SDK should work just fine (3.0.1 currently). If you use Appwrite 0.11, I believe the supported version of flutter SDK is 2.1.0.

**Comment by jsownz** [comment]
@Meldiron thanks for the info, updated appwrite to 0.12 and it's working as your described
