### ISSUE TITLE
Flutter for Web Compatibility

### ISSUE THREAD

**Issue by Blykam** [appwrite/sdk-for-flutter#5]
Is it possible to make this SDK compatible with Flutter for Web? Would be a great addition to just mobile apps

**Comment by eldadfux** [comment]
We do want to achieve this and would love any community help on this one. Seems like the biggest issue right now in order to get this done is to add web support for the [flutter web auth plugin](https://github.com/LinusU/flutter_web_auth) which we use for OAuth session creation.

**Comment by Blykam** [comment]
Okay yeah. I read your past comments on that one now. I don't think that this flutter plugin is going to be updated for web support  anytime soon.
Also I'm not a very good developer, but I learned that you can easily check the current platform in Dart/Flutter. Maybe it is possible to skip the Web Auth Plugin for Flutter Web entirely. The plugin owner mentioned a kind of a workaround for Web Auth with an iFrame and redirects. Maybe it's possible to implement that as platform specific code.

**Comment by eldadfux** [comment]
@Blykam please share your references mentioning how we can skip the plugin for the web platform?

**Comment by Blykam** [comment]
@eldadfux It's possible to check the current OS and Platform by using the dart:io Platform class. It doesn't include Web though, but  it's possible to use flutter/foundation "kIsWeb" like explained here: how-can-i-detect-if-my-flutter-app-is-running-in-the-web.
It's just an easy if-statement which determines which part of the code is executed

**Comment by lohanidamodar** [comment]
@eldadfux seems the major problem is with the [cookie_jar](https://pub.dev/packages/cookie_jar) and [dio_cookie_manager](https://pub.dev/packages/dio_cookie_manager) that is being used to manage cookies, both doesn't have support for flutter web.

Two other problems are [flutter web auth](https://pub.dev/packages/flutter_web_auth) and [package info](https://pub.dev/packages/package_info) plugins, which we might be able to bypass, but still unable to find alternative for persistence cookie jar alternative for web. So, web support might have to wait

**Comment by eldadfux** [comment]
I think that we might be able to migrate to the default http client. I’ll try to see if we can drop the package info dependency or only use it for non web platforms. The flutter web Auth package is only used for OAuth support

**Comment by lohanidamodar** [comment]
@eldadfux upon more research looks like cookies is handled automatically in web, so we can simply skip cookie related things as wells if it's web. So I am doing more testing

**Comment by lohanidamodar** [comment]
## [Update]
[https://github.com/appwrite/sdk-generator/pull/53](https://github.com/appwrite/sdk-generator/pull/53) should add support for except for oAuth on flutter web.

**Comment by eldadfux** [comment]
# Update 2

I have merged @lohanidamodar PRs and published a new prerelease of the Appwrite SDK for Flutter (0.3.0-dev.1) with web support!!

We still need to add OAuth login support for web, but it seems like this can be achievable. @dlohani and I will work on this in the next few days.

**Any help with beta testing of the new version will be appreciated**

![image](https://user-images.githubusercontent.com/1297371/92125697-f886ff80-ee07-11ea-93ea-40070b6f66f0.png)

**Comment by PsychTechApS** [comment]
Hello. You asked for beta testing of flutter web on dev channel, and I just tried to run my flutter test application (working on phone emulator) and account.createSession makes an exception: TypeErrorImpl (Expected a value of type 'DefaultHttpClientAdapter', but got one of type 'BrowserHttpClientAdapter'). In call method it goes via selfsigned=true.

**Comment by lohanidamodar** [comment]
@PsychTechApS please confirm this only occurs when you have .setSelfSigned() called on your appwrite Client.

**Comment by PsychTechApS** [comment]
@lohanidamodar I just checked. Same error occurs with selfSigned = false...

**Comment by lohanidamodar** [comment]
@PsychTechApS can you please share the screenshot of the Log exactly so that it's easier to pinpoint the issue. Thanks!

**Comment by eldadfux** [comment]
A new version with all latest updates is out: https://pub.dev/packages/appwrite/versions/0.3.0-dev.2

@PsychTechApS please check if you still get any errors.

**Comment by AlimFreight** [comment]
I had the same error but after update to latest version everything work properly.

**Comment by PsychTechApS** [comment]
I still get error, now it is "NoSuchMethodError: The getter 'uri' was called on null". (same result selfsigned or not).

**Comment by lohanidamodar** [comment]
@PsychTechApS Can you try by clearing cache, make sure pub is using the version of appwrite as you have used, sometimes it takes from cache and cause issues.

**Comment by PsychTechApS** [comment]
I did run "flutter clean" and also "flutter pub cache repair" and is still having the same error.

**Comment by lohanidamodar** [comment]
@PsychTechApS If possible the code you are running and the screenshot of the error, would be very helpful for us to reproduce. Thank you

**Comment by PsychTechApS** [comment]
I will try to make a new project just to test web with the dev channel from the beginning to see if it is specific to my current project or not. If same error occour I can share this project.
This is a screenshot of the error stack:
![billede](https://user-images.githubusercontent.com/39657431/92586743-f94fe380-f296-11ea-863a-06f4e69e6c4b.png)

**Comment by lohanidamodar** [comment]
@PsychTechApS I am not sure if this is related to AppWrite. But yes if the bug exists, anything that would help us reproduce, as what steps trigger this error, would be a great help. Thank you.

**Comment by lohanidamodar** [comment]
> I will try to make a new project just to test web with the dev channel from the beginning to see if it is specific to my current project or not. If same error occour I can share this project.
> This is a screenshot of the error stack:
> ![billede](https://user-images.githubusercontent.com/39657431/92586743-f94fe380-f296-11ea-863a-06f4e69e6c4b.png)

@PsychTechApS refering to this (https://discordapp.com/channels/564160730845151244/634237163986485249/751091287171661935) message on discord by @AlimFreight I believe your two errors are related but not related to Appwrite. Please confirm

**Comment by PsychTechApS** [comment]
@lohanidamodar I can not say if it is the same as @AlimFreight's error. I will ask him. I only know that my code works on phone emulator and not on web. But if it is only my code that breaks, just ignore my post 👍

**Comment by PsychTechApS** [comment]
@lohanidamodar - my last contribution on this subject at this time (after talking to @AlimFreight):

1. I had not to use appwrite_dev, as I thought we were supposed to do to have web compatibility, but instead: appwrite:  (on ^0.3.0-dev.2.)

2. the invalid type did not disappear, but now it is because my exception returns null (e=null): 
catch (e) {} print(e.message);

From my understanding @AlimFreight had the same typedef error as I had, but removed the .message in print(e) and got the error to disappear and has working flutter web code.

I really do not know what is going on - and have to put it to a rest.

**Comment by lohanidamodar** [comment]
@PsychTechApS No worries. Thank you for your contribution. However if you do want to continue with your project and want help, feel free to reach out any time.

**Comment by klnfreedom** [comment]
Hello everyone, I have some problem with create a document on appwrite (flutter web), when I start the process for creation, I have an error: DioError [DioErrorType.RESPONSE]: Http status error [401].
But I am authorized.
Thats a part of code of creation document:

Future<bool> uploadDataToAppwrite(GasStationFromTransnet data) async {
    var qwert = jsonEncode(data.toJson());
    try {
      Response response = await database.createDocument(
        collectionId: AppConstants.collection,
        data: data.toJson(),
        read: ["*"],
        write: ["*"],
      );
      print(response);
      return true;
    } catch (e) {
      print(e);
      return false;
    }
  }
Response is null.

Please help

**Comment by klnfreedom** [comment]
And I can read a document from appwrite, but I can't create a document to appwrite

**Comment by AlimFreight** [comment]
Yes, I have the same issue with Flutter Web app . It's somehow drop authentication right after initialization. Or something else going on  but here is the cod.

`Performing hot restart...`
`Waiting for connection from debug service on Chrome...`
`Restarted application in 364ms.`
`{"$id":"5ff4a121a409a","type":1,"expire":1641403553} `  **_------------- createSession_**
`DioError [DioErrorType.RESPONSE]: Http status error [401]`  **_------------ account.get()_**

**Comment by eldadfux** [comment]
@AlimFreight can you share the code itself? are you waiting for the create session call to complete before calling `account.get`?

**Comment by AlimFreight** [comment]
Client client;
Database database;
Account account;
bool _isLoggedIn;

class ActivateClient extends GetxController {
  bool get isLoggedIn => _isLoggedIn;

  static initClient() async {
    _isLoggedIn = false;

    client = Client();

    client
        .setEndpoint(AppConstants.endPoint)
        .setProject(AppConstants.projectId);

    account = Account(client);
    await responseAppWrite();

    database = Database(client);

    await _checkIsLoggedIn();
  }

  static Future<void> responseAppWrite() async {
    try {
      var result = await account.createSession(
        email: '*********@gmail.com',
        password: '********',
      );
      print(result);
    } catch (e) {
      print(e);
    }
  }

  static Future<void> _checkIsLoggedIn() async {
    try {
      var result = await account.get();

      print(result.toString());
    } catch (e) {
      print(e);
    }
  }
}

**Comment by lohanidamodar** [comment]
@AlimFreight @klnfreedom Thank you for trying out appwrite in Flutter Web and helping us debug issues. However, I would like your feedback on following matters.

Can you please clone [Playground for Flutter](https://github.com/appwrite/playground-for-flutter), setup the correct project and collectionId and test it, I am able to login and create document in the playground using the latest Flutter beta channel.

And, if possible any of you share following, will help us debug
1. Can any of you share a minimal reproducible code with which we can reproduce the error? 
2. Can you confirm that if you run the same code in android/ios it works, and the problem is same working code has problem when ran in web? If you are having issue in mobile platforms as well, it might be other issue
3. Can you please post your `flutter doctor` so that I can test against the same flutter version

**Comment by klnfreedom** [comment]
@lohanidamodar I share you a part of code which is included the error of Dio.Exception 401
https://github.com/klnfreedom/test_for_appwrite_flutter_web.git
On android and ios platform aren't working (Insecure HTTP is not allowed by platform: http://104.225.142.211/v1/database/collections/5ff451fd73abf/documents)

**Comment by AlimFreight** [comment]
@lohanidamodar  Thank you for you quick support. 
First off all **Flutter doctor** output.

[✓] Flutter (Channel beta, 1.25.0-8.1.pre, on macOS 11.1 20C69 darwin-x64, locale en)
    • Flutter version 1.25.0-8.1.pre at /Users/ruslan/Development/flutter
    • Framework revision 8f89f6505b (3 weeks ago), 2020-12-15 15:07:52 -0800
    • Engine revision 92ae191c17
    • Dart version 2.12.0 (build 2.12.0-133.2.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/ruslan/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.0

[✓] Connected device (3 available)
    • Android SDK built for x86 (mobile) • emulator-5554                        • android-x86    • Android 10 (API 29) (emulator)
    • iPhone 12 Pro Max (mobile)         • E655D648 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • Chrome (web)                       • chrome                               • web-javascript • Google Chrome 87.0.4280.88

• No issues found!

### **Web**  output.

Running with unsound null safety
For more information see https://dart.dev/null-safety/unsound-null-safety
Debug service listening on ws://127.0.0.1:62936/4xAmwQZYZHo=/ws
DioError [DioErrorType.RESPONSE]: Http status error [401]
{"$id":"5ff5eeea3dd4d","type":1,"expire":1641489002}
DioError [DioErrorType.RESPONSE]: Http status error [401]   ---**login with Email button pushed**
{"message":"Guest (role: guest) missing scope (documents.write)","code":401,"version":"0.6.2"} --- **Create document pushed**

### **Android output**

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':flutter_web_auth:compileDebugAidl'.
> Could not resolve all task dependencies for configuration ':flutter_web_auth:debugCompileClasspath'.
   > Could not resolve androidx.lifecycle:lifecycle-common:{strictly 2.0.0}.
     Required by:
         project :flutter_web_auth
      > Cannot find a version of 'androidx.lifecycle:lifecycle-common' that satisfies the version constraints: 

### **iOS output**

2021-01-06 11:37:10.035027-0600 Runner[79826:638552] Metal API Validation Enabled
2021-01-06 11:37:10.180398-0600 Runner[79826:640080] flutter: Observatory listening on http://127.0.0.1:50349/EZoGfDlkfww=/
2021-01-06 11:37:10.686085-0600 Runner[79826:640070] fopen failed for data file: errno = 2 (No such file or directory)
2021-01-06 11:37:10.686221-0600 Runner[79826:640070] Errors found! Invalidating cache...
2021-01-06 11:37:11.256117-0600 Runner[79826:640070] fopen failed for data file: errno = 2 (No such file or directory)
2021-01-06 11:37:11.256209-0600 Runner[79826:640070] Errors found! Invalidating cache...
2021-01-06 11:37:12.080979-0600 Runner[79826:640069] flutter: DioError [DioErrorType.DEFAULT]: Bad state: Insecure HTTP is not allowed by platform: http://105.105.*.*/v1/account
#0      _HttpClient._openUrl (dart:_http/http_impl.dart:2435:7)
#1      _HttpClient.openUrl (dart:_http/http_impl.dart:2342:7)
#2      DefaultHttpClientAdapter.fetch (package:dio/src/adapters/io_adapter.dart:35:40)
#3      DioMixin._dispatchRequest (package:dio/src/dio.dart:922:46)
<asynchronous suspension>
#4      DioMixin._request._interceptorWrapper.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:dio/src/dio.dart)
<asynchronous suspension>
2021-01-06 11:37:31.542635-0600 Runner[79826:640069] flutter: Bad state: Insecure HTTP is not allowed by platform: http://105.105.*.*/v1/account/sessions
2021-01-06 11:37:52.397277-0600 Runner[79826:640069] flutter: null

**Comment by eldadfux** [comment]
> @lohanidamodar I share you a part of code which is included the error of Dio.Exception 401
> https://github.com/klnfreedom/test_for_appwrite_flutter_web.git
> On android and ios platform aren't working (Insecure HTTP is not allowed by platform: http://104.225.142.211/v1/database/collections/5ff451fd73abf/documents)

The insecure HTTP error can be resolved by using the `setSelfSigned` method here:
https://github.com/klnfreedom/test_for_appwrite_flutter_web/blob/e18b1eef6331affd1022e3e197357cf89e6acca1/lib/app/client/client_init.dart#L12

```dart
    client
        .setEndpoint(AppConstants.endPoint)
        .setProject(AppConstants.projectId)
        .setSelfSigned()
;
```

**Comment by AlimFreight** [comment]
> > @lohanidamodar I share you a part of code which is included the error of Dio.Exception 401
> > https://github.com/klnfreedom/test_for_appwrite_flutter_web.git
> > On android and ios platform aren't working (Insecure HTTP is not allowed by platform: http://104.225.142.211/v1/database/collections/5ff451fd73abf/documents)
> 
> The insecure HTTP error can be resolved by using the `setSelfSigned` method here:
> https://github.com/klnfreedom/test_for_appwrite_flutter_web/blob/e18b1eef6331affd1022e3e197357cf89e6acca1/lib/app/client/client_init.dart#L12
> 
> ```dart
>     client
>         .setEndpoint(AppConstants.endPoint)
>         .setProject(AppConstants.projectId)
>         .setSelfSigned()
> ;
> ```

It's already set on in [Playground for Flutter](https://github.com/appwrite/playground-for-flutter)

**Comment by eldadfux** [comment]
@AlimFreight I have a feeling we're mixing multiple issues in this thread. Is your problem only on Flutter Web integration?

**Comment by AlimFreight** [comment]
> @AlimFreight I have a feeling we're mixing multiple issues in this thread. Is your problem only on Flutter Web integration?

Yes , but as @lohanidamodar  asked I did check [Playground for Flutter](https://github.com/appwrite/playground-for-flutter) for all platforms on environment.

**Comment by eldadfux** [comment]
After creating an account session on the browser can you see if a cookie was set?

**Comment by AlimFreight** [comment]
No cookies wasn't set 
![image](https://user-images.githubusercontent.com/54543689/103824324-4bccc100-5039-11eb-82fc-0daf3b05e9af.png)

**Comment by eldadfux** [comment]
@AlimFreight I seem to be able to persist a session using a cookie on the playground:
![image](https://user-images.githubusercontent.com/1297371/103827064-ce2ca380-5080-11eb-8a2e-7346764d90a5.png)

The cookie is only visible when I view the devtools cookies on the Appwrite console. The cookie name should be: `a_session_[PROJECT-ID]`, can you see it? when you try to fetch the user account do you see the cookie as part of the `Cookies` header?

**Comment by AlimFreight** [comment]
![image](https://user-images.githubusercontent.com/54543689/103829467-8554fa80-5040-11eb-896c-3ba6ca3c27ba.png)

**Comment by eldadfux** [comment]
@AlimFreight I doubled check the issue with both 0.6.2 and 0.7.0 and both seems to work for me, but I do have an idea. Can you switch your Appwrite endpoint from the IP address to localhost or a domain name and see if it works?

**Comment by AlimFreight** [comment]
@eldadfux  I can't switch to localhost because it's VPS, but I can move my domain name to that host. Another idea to invite you to my AppWrite instance then you can check it by yourself.

**Comment by eldadfux** [comment]
I can confirm that when I switch from localhost to my private ip, i can reproduce the issue.

**Comment by AlimFreight** [comment]
Ok , then I definitely have to switch to domain name for now on.

**Comment by AlimFreight** [comment]
After I've changed to domain name I got this
```
Request URL: http://104-225-142-211.cloud-xip.io/v1/account
Request Method: GET
Status Code: 401 Unauthorized
Remote Address: 104.225.142.211:80
Referrer Policy: no-referrer-when-downgrade
```

**Comment by lohanidamodar** [comment]
@eldadfux @AlimFreight @klnfreedom 
Unable to decide the problem. I am able to run perfectly when I switch to my local instance, even https://github.com/klnfreedom/test_for_appwrite_flutter_web.git project fine on localhost. However using the project details provided in the repository, I can reproduce the error. Even after I set the domain name locally, I can reproduce the error as @AlimFreight  said. 

We might need to boot up a VPS to do some more testing regarding this.

**Comment by lohanidamodar** [comment]
@AlimFreight @klnfreedom 
we believe the issue is with different domain cookie policy as the app is running in localhost and the server is different. That is why it worked on our localhost. However, with chrome, it only blocks cross-site cookies in insecure mode. From the information above I can see that both of you are using `http` and not `https`. 

For us, switching the `https` did the trick, we were able to fix the issue. So we suggest make the following changes and test and let us know if it works
1. In the chrome instance opened by `flutter run`, clear all existing cookies
2. Access the Appwrite console with `https`, it will give some kind of insecure connection error, you need to tap on `advance` and accept to proceed so that you are able to access the Appwrite console over `https`
3. Finally, in your flutter code in endpoint switch to `https`  instead of `http`

These steps has resolved issues for us, please let us know whether it works for you, whether it provides a separate error?

Thank you for your support.

**Comment by AlimFreight** [comment]
@lohanidamodar 
Thank you , after I did that everything is working. And I changed web platform to https in AppWrite console as well.

**Comment by lohanidamodar** [comment]
Awesome @AlimFreight Thank you fro your response and support.

**Comment by eldadfux** [comment]
Flutter web support should be pretty good now. If any problems are found, please open a new issue.
