### ISSUE TITLE
🐛 Bug Report: Error when widget binding is not initialized

### ISSUE THREAD

**Issue by jonorozcoc** [appwrite/sdk-for-flutter#52]
### 👟 Reproduction steps

- Create a flutter project
- Create appwrite project and add flutter platform
- Install appwrite package to flutter project
- Initialize client as explained on example or readme

### 👍 Expected behavior

Connect to appwrite server

### 👎 Actual Behavior

Throwing exception
Null check operator used on a null value

### 🎲 Appwrite version

Different version (specify in environment)

### 💻 Operating system

Windows

### 🧱 Your Environment

Appwrite version: 3.0.1

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by jonorozcoc** [comment]
FYI, I've fixed the issue with this line before client initialization:

`  WidgetsFlutterBinding.ensureInitialized();`

If you want I can make a PR to update the docs

**Comment by lohanidamodar** [comment]
When you use `async` and `await` features in Flutter applications `main` function, you have to provide `WidgetsFlutterbinding.ensureInitialized()`.
