### ISSUE TITLE
message: User (role: guest) missing scope (files.write), code: 401

### ISSUE THREAD

**Issue by ksmk007** [appwrite/sdk-for-flutter#53]
Future res = storage.createFile(
        file: await MultipartFile.fromFile(file.path, filename: file.name),
        read: [],
        write: [],
      );

message: User (role: guest) missing scope (files.write), code: 401, version: 0.12.3

not write 

how to solve this problem

_Originally posted by @ksmk007 in https://github.com/appwrite/sdk-for-flutter/issues/35#issuecomment-1058026223_

**Comment by lohanidamodar** [comment]
@ksmk007 you need to have an active session in order to be able to create a file, are you logged in?

**Comment by lohanidamodar** [comment]
Closing as no new information!
