### ISSUE TITLE
How to make a fuzzy query？

### ISSUE THREAD

**Issue by OHeroJ** [appwrite/sdk-for-flutter#58]
```dart
Query.search("title", searchKey!)
```

return nothing

**Comment by lohanidamodar** [comment]
@OHeroJ Please explain.

**Comment by OHeroJ** [comment]
@lohanidamodar How to use like queries similar to sql?

```sql
select * from table1 where name like '%hello%'
```

**Comment by lohanidamodar** [comment]
`Query.search("title", searchKey!)` should work if search key is `hello`. Please share the data set you have and code you are using.
