### ISSUE TITLE
🐛 Bug Report:  Flutter Windows Concurrent Modification Error

### ISSUE THREAD

**Issue by kekavc24** [appwrite/sdk-for-flutter#59]
### 👟 Reproduction steps

When I try `database.list()`  with Queries or `teams.getMemberships()`  throws a ` Unhandled Exception: AppwriteException: null, Concurrent modification during iteration: Instance(length:2) of '_GrowableList'`

### 👍 Expected behavior

It should fetch the polled results normally with results like in Flutter Android, iOS and Web.

### 👎 Actual Behavior

Constantly throws a ` Unhandled Exception: AppwriteException: null, Concurrent modification during iteration: Instance(length:2) of '_GrowableList'` or may not. It was hard understanding the behaviour. When I debugged with VS Code debugger it shows that the cascade :

 `dart:_internal/iterable.dart file` in flutter `line 336` which throws the `Concurrent modification error` => triggered by `client_io.dart` at `line 180` which is iterating i think => triggered by `line 251` still in `client_io.dart` which throws the error at `line 264` in same file => my code..

### 🎲 Appwrite version

Different version (specify in environment)

### 💻 Operating system

Windows

### 🧱 Your Environment

Version 0.13.4

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by lohanidamodar** [comment]
Duplicate https://github.com/appwrite/sdk-generator/issues/417
