### ISSUE TITLE
Collection not found after create the document on the Collection "Userdata" database

### ISSUE THREAD

**Issue by patricktslee** [appwrite/sdk-for-flutter#6]
Hi All,

I tried to create the document on database.  I created Collection "Userdata" and get the collectionID.  After run the below createUser function.  I got the error Collection not found.  But I have provided the collectionID.  What happen on the AppWrite server or on my code?

```
  Client appwriteClient = Client();

  appwriteClient
        .setEndpoint(appWriteServerUrl)
        .setProject(_projectId)
        .setSelfSigned();
  account = Account(appwriteClient);
  database = Database(appwriteClient);
  storage = Storage(appwriteClient);

  createUser({String username}) {
    dynamic _data;
    _data = {"username": username};
    Future result = database.createDocument(
      collectionId: '5f2c17b7d74ae',
      data: _data,
      read: [],
      write: [],
    );

    result.then((response) {
      print("create user in Users database success====================");
      print(response);
    }).catchError((error) {
      print("create user in Users database error====================");
      print(error.response);
    });
  }

```

Error throw on below

```
flutter: create user in Users database error====================
flutter: {"message":"Collection not found","code":404,"version":"0.6.2"}

```
![Screenshot 2020-08-06 at 10 54 03 PM](https://user-images.githubusercontent.com/8926578/89547400-48d66600-d838-11ea-9c05-516760ae0a53.png)

**Comment by eldadfux** [comment]
@patricktslee check your collection permissions:

![image](https://user-images.githubusercontent.com/1297371/89574400-bed8ce00-d834-11ea-8a55-b3b75dc0388c.png)

**Comment by patricktslee** [comment]
Hi Eldadfux,

I added * for both Read and Write Access.  But I got another error "flutter: {"message":"Unauthorized action","code":401,"version":"0.6.2"}".  Actually, my logic is create user, upload the image and create database document.  Create user and upload the image are successfully.  However create database document fail.  What happen again on server or my code?

```
flutter: Initial the Chat AppWrite
flutter: Starting Signup====================
flutter: Initial the Chat AppWrite
flutter: create account success====================
flutter: {"$id":"5f2d6a84b2528","email":"joni4@gmail.com","registration":1596811908,"name":"Joni4","roles":["*","user:","role:0"]}
flutter: 5f2d6a84b2528
flutter: Trying to login
flutter: Login success====================
flutter: Get login success====================
flutter: Joni4
flutter: file.path----------/Users/patrick/Library/Developer/CoreSimulator/Devices/E15F6EA6-8D1F-4E79-9867-86AB8CDEE10D/data/Containers/Data/Application/27836D22-50BF-4EA0-B886-3A5AE4CF358D/tmp/image_picker_9867AF64-6491-4320-B11F-350A6F30D8DC-26320-0001653B5CEDD5CF.jpg
flutter: create user in Users database error====================
flutter: {"message":"Unauthorized action","code":401,"version":"0.6.2"}

flutter: success====================
flutter: {"$id":"5f2d6a8a49fe3","$permissions":{"read":["user:5f2d6a84b2528"],"write":["user:5f2d6a84b2528"]},"$collection":"files","dateCreated":1596811914,"folderId":"","name":"5f2d6a84b2528.jpg","path":"/storage/uploads/app-5f266d4fb3846/5/f/2/d/5f2d6a8a4141b.jpg","signature":"b664265e8d47bc5b426e8394bc4c0881","mimeType":"image/jpeg","sizeOriginal":15027,"sizeActual":15124,"algorithm":"gzip","token":"8485404cbc02709b1fddd798f0c73e538896b8e82b8a4d450916c29cf15e09291d7b65cc4699e30c70ea403a803ffd872f76546c3d8abc6aacccf4c7b22e35d9","comment":"","fileOpenSSLVersion":"1","fileOpenSSLCipher":"aes-128-gcm","fileOpenSSLTag":"44d2c101977370275ae9ca4ec89b2901","fileOpenSSLIV":"1164f5c71d5429440b143882"}

```

![Screenshot 2020-08-07 at 10 56 56 PM](https://user-images.githubusercontent.com/8926578/89658624-5ad00b80-d901-11ea-846c-5705a74eed1e.png)

Thanks

Patrick Lee

**Comment by eldadfux** [comment]
@patricktslee please share your request data, and specifically the document data you're trying to post to the database API.

**Comment by patricktslee** [comment]
@eldadfux 

Here is my code to createdoucment.  It is simple data {"username": username}.  

```
  createUser({String username}) {
    dynamic _data;
    _data = {"username": username};
    Future result = database.createDocument(
      collectionId: '5f2c17b7d74ae',
      data: _data,
      read: [],
      write: [],
    );

    result.then((response) {
      print("create user in Users database success====================");
      print(response);
    }).catchError((error) {
      print("create user in Users database error====================");
      print(error.response);
    });
  }

```
And here is my rule on server.  The data type of username is text.

![Screenshot 2020-08-08 at 11 03 52 AM](https://user-images.githubusercontent.com/8926578/89701162-e8921200-d966-11ea-9343-85ef22bc865e.png)

The error message
```
flutter: create user in Users database error====================
flutter: {"message":"Unauthorized action","code":401,"version":"0.6.2"}

```
Thanks

Patrick Lee

**Comment by eldadfux** [comment]
@patricktslee just add read and write permission when sending the document, '*' for wildcard access or 'user:[user_id]' should be fine.

![image](https://user-images.githubusercontent.com/1297371/89703760-597cfe00-d956-11ea-924d-d60d8b9af34e.png)

**Comment by patricktslee** [comment]
@eldadfux It works.  Thanks your help.

**Comment by eldadfux** [comment]
🥳 your'e welcome, feel free to join us on https://appwrite.io/discord in case you need more help or advice
