### ISSUE TITLE
🐛 Bug Report: Users not found

### ISSUE THREAD

**Issue by pixeluvw** [appwrite/sdk-for-flutter#60]
### 👟 Reproduction steps

Hi,

This code "Users users = Users(client);" does not work with flutter SDK. Is there a difference between dart and flutter SDK? Since this same chunk of code is working with dart sdk

### 👍 Expected behavior

Dart or flutter normally share same code

### 👎 Actual Behavior

Users not defined in flutter appwrite package 

### 🎲 Appwrite version

Different version (specify in environment)

### 💻 Operating system

Linux

### 🧱 Your Environment

I am using digital ocean 

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by 2002Bishwajeet** [comment]
Users API is basically something that would be found on server side. so you won't find this API class in the flutter_appwrite . And yes there is a difference between `[flutter_appwrite](https://pub.dev/packages/appwrite)` and `[dart_appwrite](https://pub.dev/packages/dart_appwrite)` . Flutter appwrite SDK contains all the APIs for the client side while the Dart appwrite SDK is used for performing server side functions.  If you look at the docs you can notice that some functions are different in server and client side SDK.

Also if you look at the [docs](https://appwrite.io/docs/server/users?sdk=dart-default), you will see it only on the server side only.

**Comment by pixeluvw** [comment]
Actually I was trying to undestand the code bellow which by the way found in the flutter sdk
```
Users users = Users(client);

try {
  final response = await users.create(userId: '[USER_ID]', email: ‘email@example.com’,password: ‘password’, name: ‘name’);
  print(response.data);
} on AppwriteException catch(e) {
  //show message to user or do other operation based on error as required
  print(e.message);
}
```

**Comment by 2002Bishwajeet** [comment]
This creates a new user on the server side.  And you will find this code in the [`dart package`](https://github.com/appwrite/sdk-for-dart/blob/master/lib/services/users.dart) .

**Comment by stnguyen90** [comment]
@2002Bishwajeet, thanks for chiming in on this!

@pixeluvw, is there anything else you need for this or can it be closed?

**Comment by pixeluvw** [comment]
That's fine for me thanks

**Comment by pixeluvw** [comment]
Thanks again
