### ISSUE TITLE
🐛 Bug Report: Unable to receive any messages from realtime

### ISSUE THREAD

**Issue by Hu-Wentao** [appwrite/sdk-for-flutter#61]
### 👟 Reproduction steps

I wrote realtime code with reference to the document, but I still can't receive any messages. 
Can someone provide a example project for reference?
// DI code
```dart
/// .... other ....
  @lazySingleton
  Client get client => Client()
    ..setEndpoint("http://localhost/v1")
    ..setProject("<my-proj-id>")
    ..setSelfSigned(status: true); 

  // Register User
  @lazySingleton
  Account get account => Account(sl<Client>());

  // Subscribe to files channel
  @lazySingleton
  Realtime get realtime => Realtime(sl<Client>());

/// .... other ....
````

```dart
// run on user logged in
  final rl = sl<Realtime>() // get Realtime from DI, This is valid for `database`, `account` and other components
      ..subscribe(const [
        'account',
        'collections',
        'users',
        'database',
        'documents',
        'documents.<some-doc-id>',
      ]).stream.listen((event) {
        print("debug realtime# event: ${event.events}, ${event.payload}");
      });
```
I have tried to modify the account name, create a new collection, modify the collection properties, add documents, modify the contents of documents and so on, but I can't receive any messages from realtime.
(Of course, the read and write permissions of the collection are `role:all`, and I have tried `user:XXXX`, which has no effect)

### 👍 Expected behavior

print any event message from realtime.

### 👎 Actual Behavior

on windows clinet and flutter web(chrome)
```sh
subscription: ws://localhost/v1/realtime?project=<my-proj-od>&channels%5B%5D=account&channels%5B%5D=collections&channels%5B%5D=users&channels%5B%5D=database&channels%5B%5D=documents&channels%5B%5D=documents.<some-doc-id>
```

### 🎲 Appwrite version

Different version (specify in environment)

### 💻 Operating system

Windows

### 🧱 Your Environment

server:
- Centos-Docker / Windows10-WSL2-Docker
- appwrite: 0.13.4 / 0.14.0(can not be used)

client:
- Windows10
- appwrite(flutter): 4.0.2 

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
Some questions:

1. You only have 1 instance if Client?
2. You're calling subscribe after logging in and then creating/updating documents, but you don't see any event?
3. Can you inspect the websocket messages to see what's being sent/received? In Chrome, you should be able to see this in the Network logs

FYI, the following channels don't exist:

1. collections
2. users
3. database
4. documents.<some-doc-id>

Docs on channels: https://appwrite.io/docs/realtime#channels

Also, if you're on 0.13.4, there is no `event.events`. It's just `event.event`.

**Comment by Hu-Wentao** [comment]
Thanks for the answer !
I used the "playground-for-flutter" project, which worked. 
Maybe this project should be used as the first recommended example  :）
