### ISSUE TITLE
🚀 Feature: Url to view file in addition to uInt8List

### ISSUE THREAD

**Issue by hey-nicolasklein** [appwrite/sdk-for-flutter#63]
### 🔖 Feature description

I'm currently developing a Flutter App for mobile, web and desktop. Each platform has it's unique challenges. Currently I'm trying to play video from my appwrite backend. While it is no problem to create a local file from a byteList on mobile and play a video from it, there is no play from file on web.

Of course, I can call the appwrite rest Api with the /view directive and view the file in my browser. What about some way to get the URL to pass it to a audio or video player on web.

As I can see, the `getFileDownload` and `getFileView` methods do basically the same thing in the Appwrite Flutter SDK. 

### 🎤 Pitch

What if `getFileView` would actually return a URL to access the File. The URL could be passed to any Video or Audio Player package and would make the appwrite flutter sdk work better on web.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by lohanidamodar** [comment]
@hey-nicolasklein For now you can construct the URL yourself easily. Here's the trick

`[YOUR_ENDPOINT]/storage/buckets/{bucketId}/files/{fileId}/preview?project=[PROJECT_ID]`.

Make sure to use the endpoint. If you do this, you need to make the file public.

**Comment by hey-nicolasklein** [comment]
Hey @lohanidamodar thanks for the trick. But I really would like to use authentication. My project guidelines do not allow to make the files public. Is there any other solution?

**Comment by lohanidamodar** [comment]
> Hey @lohanidamodar thanks for the trick. But I really would like to use authentication. My project guidelines do not allow to make the files public. Is there any other solution?

Generating JWT for user and passing `jwt=token` as the query parameter might work (not completely sure). But we are working on solving this automatically in the SDKs as well.

**Comment by hey-nicolasklein** [comment]
Can you explain what you mean by putting project as the query parameter? 
You mean like `...{fileId}/preview?jwt=token?project=[PROJECT_ID]`?

**Comment by lohanidamodar** [comment]
Yes like this.
`..{fileId}/preview?jwt=token&project=[PROJECT_ID]?`

**Comment by hey-nicolasklein** [comment]
Can I get the JWT Token from the current session (in the Flutter SDK)?

**Comment by lohanidamodar** [comment]
> Can I get the JWT Token from the current session (in the Flutter SDK)?

You can by calling `account.createJWT` after you have an active session
