### ISSUE TITLE
🐛 Bug Report: Failed to get the Session object from Future<Session>

### ISSUE THREAD

**Issue by patricktslee** [appwrite/sdk-for-flutter#65]
### 👟 Reproduction steps

Have you experienced the issue on Flutter to run Appwrite "Get Session By ID"? I tried to setup the getSession method on below.  But it looks like that it is failed to get the Session object from Future<Session>.  Please see my below code and debug console message.

```
  Future<String> getSession(String? sessionID) async {
    _debug(
        "At ${DateTime.now()} getSession($sessionID) => Starting ApiService getSession()");
    String _result = "result";

    try {
      Future result = account!.getSession(sessionId: sessionID!);

      _debug(
          "At ${DateTime.now()} getSession($sessionID) result type is ${result.runtimeType}");
      result.then((response) {
        _debug("getSession($sessionID) response is");
//        _result = response.toString();
        _debug("getSession($sessionID) _result is $_result");
      }).catchError((error) {
        _debug("getSessions() error is ${(error.response)}");
      });
    } on AppwriteException catch (exception, stackTrace) {
      _debug("getSession($sessionID) fail!");
      _debug(stackTrace.toString());
      await Sentry.captureException(
        exception,
        stackTrace: stackTrace,
      );
    }
    _debug(
        "At ${DateTime.now()} getSession($sessionID) => Completed ApiService getSession()");
    return _result;
  }

```

Debug console message

```
I/flutter ( 5925): At ApiService class - At 2022-05-30 11:46:21.507695 getSession(6294396a991339db8d84) => Starting ApiService getSession()
I/flutter ( 5925): │ :bulb: At ApiService class - At 2022-05-30 11:46:21.507695 getSession(6294396a991339db8d84) => Starting ApiService getSession()
I/flutter ( 5925): At ApiService class - At 2022-05-30 11:46:21.525700 getSession(6294396a991339db8d84) result type is Future<Session>
I/flutter ( 5925): │ :bulb: At ApiService class - At 2022-05-30 11:46:21.525700 getSession(6294396a991339db8d84) result type is Future<Session>
I/flutter ( 5925): At ApiService class - At 2022-05-30 11:46:21.539364 getSession(6294396a991339db8d84) => Completed ApiService getSession()
I/flutter ( 5925): │ :bulb: At ApiService class - At 2022-05-30 11:46:21.539364 getSession(6294396a991339db8d84) => Completed ApiService getSession()

```

It can't find the "getSession($sessionID) response is" message in debug console.

I captured the error when the Session is loaded..  It looks like providerAccessTokenExpiry is null and cause the exception throw.  As this is the Anonymous User, should the providerAccessTokenExpiry be null?

![image](https://user-images.githubusercontent.com/8926578/171312918-70aa12b4-e134-4fd4-92ad-b9649deb6501.png)

I am using   appwrite: ^5.0.0

### 👍 Expected behavior

Return the Session information

### 👎 Actual Behavior

Not return Session information

### 🎲 Appwrite version

Version 2.0.x

### 💻 Operating system

Windows

### 🧱 Your Environment

I use the vscode in Windows 11

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by lohanidamodar** [comment]
@patricktslee What is the Appwrite Server version? The latest appwrite package works with lates version of Appwrite only. Please confirm you are using the latest version of Appwrite server.

**Comment by patricktslee** [comment]
> @patricktslee What is the Appwrite Server version? The latest appwrite package works with lates version of Appwrite only. Please confirm you are using the latest version of Appwrite server.

The appwrite server version is version 0.13.4.304. What is the flutter Appwrite package version for these appwrite server version?

**Comment by 2002Bishwajeet** [comment]
Hey @patricktslee , you must use `4.0.2` version

**Comment by lohanidamodar** [comment]
@patricktslee colsing this as resolved. Use the suggested version. You can always check the SDK Readme which lists the compatible server version.
