### ISSUE TITLE
Add Windows support for the Appwrite Flutter SDK

### ISSUE THREAD

**Issue by eldadfux** [appwrite/sdk-for-flutter#8]
Most features of the Appwrite Flutter SDK should already work with Windows apps out of the box. One specific area that still lacks support is our OAuth login. For us to enable OAuth login we actually need to add Windows support on the Web auth plugin https://github.com/LinusU/flutter_web_auth we use as a dependency.

The Web Auth library already support web auth login for Android, iOS, and MacOS. Once Windows support is added, we should just update the Appwrite SDK to use the latest version of the auth plugin.

This actual PR should be made against https://github.com/LinusU/flutter_web_auth, but will be happy to make this issue valid for Appwrite SWAG during Hacktoberfest.

**Comment by jocubeit** [comment]
This issue can now be closed as we moved to flutter_web_auth_2 here https://github.com/appwrite/sdk-generator/pull/527
