### ISSUE TITLE
🚀 Feature: Improve Pub Points on pub.dev

### ISSUE THREAD

**Issue by stnguyen90** [appwrite/sdk-for-flutter#88]
### 🔖 Feature description

pub.dev score: https://pub.dev/packages/appwrite/score

1. [ ] Use an OSI-approved license. Sample projects with a valid [BSD-3](https://opensource.org/licenses/BSD-3-Clause) license
    * [url_launcher](https://github.com/flutter/plugins/blob/main/packages/url_launcher/url_launcher/LICENSE) 
    * [device_info_plus](https://github.com/fluttercommunity/plus_plugins/blob/main/packages/device_info_plus/device_info_plus/LICENSE)
    * [intl](https://github.com/dart-lang/intl/blob/master/LICENSE)
3. [ ] Code has no errors, warnings, lints, or formatting issues

### 🎤 Pitch

Packages with a higher pub points look better.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
For the static analysis problem:

> INFO: Avoid using web-only libraries outside Flutter web plugin packages.

we can try using [universal_html](https://stackoverflow.com/questions/60646793/avoid-using-web-only-libraries-outside-flutter-web-plugin-packages).

**Comment by niteshsh4rma** [comment]
Hi @stnguyen90, I would like to work on this, can you add me as assignee ?

**Comment by stnguyen90** [comment]
Thanks for your interest, @niteshsh4rma! Please make sure to make the change in the [SDK Generator](https://github.com/appwrite/sdk-generator) repo.
