### ISSUE TITLE
Add Linux support for the Appwrite Flutter SDK

### ISSUE THREAD

**Issue by eldadfux** [appwrite/sdk-for-flutter#9]
Most features of the Appwrite Flutter SDK should already work with Linux apps out of the box. One specific area that still lacks support is our OAuth login. For us to enable OAuth login we actually need to add Linux support on the Web auth plugin https://github.com/LinusU/flutter_web_auth we use as a dependency.

The Web Auth library already support web auth login for Android, iOS, and MacOS. Once Linux support is added, we should just update the Appwrite SDK to use the latest version of the auth plugin.

This actual PR should be made against https://github.com/LinusU/flutter_web_auth, but will be happy to make this issue valid for Appwrite SWAG during Hacktoberfest.

**Comment by arshita129** [comment]
Hey! I want to try to solve this. But being a beginner, can u please suggest from where can I start?

**Comment by eldadfux** [comment]
I suggest you try and contact the maintainers or submit a PR at: https://github.com/LinusU/flutter_web_auth

**Comment by luis-cruzt** [comment]
Looks like there's an open PR at: https://github.com/LinusU/flutter_web_auth/pull/74

**Comment by dj3364** [comment]
Yes23

**Comment by hemangjoshi37a** [comment]
I this can be closed as running the docker container already solves this problem.

**Comment by lohanidamodar** [comment]
Closing this, as the lastest version of `flutter_web_auth_2` should have already added this feature. If there is any further issues, feel free to reopen.
