### ISSUE TITLE
🐛 Bug Report: You've forgotten to add unit tests to the repo

### ISSUE THREAD

**Issue by xni06** [appwrite/sdk-for-flutter#90]
### 👟 Reproduction steps

Look for unit tests...

### 👍 Expected behavior

Expect to see some unit tests

### 👎 Actual Behavior

There aren't any unit tests :-(

### 🎲 Appwrite version

Version 2.0.x

### 💻 Operating system

MacOS

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by lohanidamodar** [comment]
@xni06 Thank you for raising the issue. We do welcome the contribution if anyone is interested. However, the unit tests will have to be written in our https://github.com/appwrite/sdk-generator As our SDKs are generated from swagger specs, we need to generate relevant tests using the specs as well. We do plan on adding tests to all our SDKs.

**Comment by xni06** [comment]
>However, the unit tests will have to be written in our https://github.com/appwrite/sdk-generator
I'm talking about unit tests for the Flutter app, not the `sdk-generator`.

**Comment by Shiba-Kar** [comment]
```dart
 static Future<Profile?> updateProfile(
    Account account,
    Databases databases,
    Profile profile,
  ) async {
    try {
      final user = await account.get();
      final doc = await databases.createDocument(
        databaseId: userDatabaseID,
        collectionId: profileCollectionID,
        documentId: user.$id,
        data: profile.toJson(),
        permissions: [Permission.read(Role.users())],
      );

      return Profile.fromJson(doc.data);
    } on AppwriteException catch (e) {
      Utils.debLog(e);
      return null;
    }
  }

```
How can I test this peace of code in the test folder ?

**Comment by xni06** [comment]
> ```dart
>  static Future<Profile?> updateProfile(
>     Account account,
>     Databases databases,
>     Profile profile,
>   ) async {
>     try {
>       final user = await account.get();
>       final doc = await databases.createDocument(
>         databaseId: userDatabaseID,
>         collectionId: profileCollectionID,
>         documentId: user.$id,
>         data: profile.toJson(),
>         permissions: [Permission.read(Role.users())],
>       );
> 
>       return Profile.fromJson(doc.data);
>     } on AppwriteException catch (e) {
>       Utils.debLog(e);
>       return null;
>     }
>   }
> ```
> 
> How can I test this peace of code in the test folder ?

Inject the dependencies; use https://pub.dev/packages/fake_cloud_firestore; verify/expect the outcome

**Comment by Shiba-Kar** [comment]
@xni06 not working with firebase , I am working with Appwrite Databases

**Comment by xni06** [comment]
> @xni06 not working with firebase , I am working with Appwrite Databases

It's the same principle - fake it

**Comment by lohanidamodar** [comment]
@xni06 We have now added unit tests with our SDK, we have about 73% test coverage.
