### ISSUE TITLE
🚀 Feature:  Developer environment (Online IDE)

### ISSUE THREAD

**Issue by AnirudhDaya** [appwrite/sdk-for-flutter#98]
### 🔖 Feature description

Hello maintainers.
I would like to add gitpod to your repo to help beginners contribute.

- Gitpod is an online IDE which can be launched from any GitHub page. Within seconds, Gitpod provides a fully working development environment, including a VS Code-powered IDE and a cloud-based Linux container explicitly configured for the project
- I have seen one of your [repo](https://github.com/appwrite/appwrite#one-click-setups) adopt gitpod to help new contributors in their open-source journey. It's hassle-free. You don't need to worry about dependencies not being present, since gitpod does all the heavy lifting.

I can add a badge to your repo in the [CONTRIBUTING.md](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md) file similar to this one:
<a href="https://gitpod.io/#<your-repository-url>">
  <img
    src="https://img.shields.io/badge/Contribute%20with-Gitpod-908a85?logo=gitpod"
    alt="Contribute with Gitpod"
  />
</a>

### 🎤 Pitch

- Gitpod is highly contextual, such that it opens the IDE in the correct mode depending on the context:
   -  If you are looking at a particular file of a certain commit on GitHub, starting a Gitpod workspace will check out the right version and open the file you’ve been looking at in the IDE.

   - Starting a Gitpod workspace from an issue will automatically create a branch and preconfigure the commit message.
- Once you are in the IDE, you can interact with GitHub in various ways. Besides the obvious Git integration, you can do things like commenting inline in editors, approving and even merging PRs.

### 👀 Have you spent some time to check if this issue has been raised before?

- [x] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@AnirudhDaya, thanks for your interest! 🙏 Unfortunately, this is a read only repo and people shouldn't be developing directly against it so it doesn't quite make sense to add gitpod to this.

**Comment by AnirudhDaya** [comment]
Oh sorry my bad.
Is there any repo of appwrite which needs gitpod? If yes could you suggest them?

**Comment by stnguyen90** [comment]
@AnirudhDaya I don't think there's anything extra needed for gitpod for any of our repos.
